#!/bin/bash
# Set up benchmark repos for the current SKILL.md version.
#
# Default: copies from clean/ (pristine shallow clones) and docs_gathered/<repo>/
# (curated specification documents). This ensures zero contamination from prior runs.
#
# Fallback: if clean/<repo> doesn't exist, falls back to copying from the most
# recent prior version (the old behavior), with a loud warning.
#
# Usage:
#   ./setup_repos.sh              # All known repos
#   ./setup_repos.sh chi httpx    # Specific repos
#   ./setup_repos.sh --from-prior chi httpx   # Force old copy-from-latest behavior
#
# Prerequisites:
#   ./create_clean_repos.sh       # Populate clean/ (one-time)
#
# After setup, run (defaults: Copilot, gpt-5.4, parallel, single-pass, no seeds):
#   python3 ../bin/run_playbook.py chi httpx        # bare names → version-append fallback
#   python3 ../bin/run_playbook.py chi-1.4.5        # explicit versioned directory

set -euo pipefail
source "$(dirname "$0")/_benchmark_lib.sh"

ALL_REPOS=(chi cobra express gson httpx javalin serde zod virtio okhttp axum pydantic)
FROM_PRIOR=false

# Parse flags
POSITIONAL=()
for arg in "$@"; do
    case "$arg" in
        --from-prior) FROM_PRIOR=true ;;
        *) POSITIONAL+=("$arg") ;;
    esac
done

if [ ${#POSITIONAL[@]} -gt 0 ]; then
    REPOS=("${POSITIONAL[@]}")
else
    REPOS=("${ALL_REPOS[@]}")
fi

VERSION=$(detect_skill_version)
[ -z "$VERSION" ] && echo "ERROR: Can't detect version from SKILL.md" && exit 1

CLEAN_DIR="${SCRIPT_DIR}/clean"
DOCS_DIR="${SCRIPT_DIR}/docs_gathered"

echo "=== Quality Playbook — Repo Setup ==="
echo "Version: ${VERSION}"
echo "Source:  $([ "$FROM_PRIOR" = true ] && echo "prior version (--from-prior)" || echo "clean/")"
echo "Repos:   ${REPOS[*]}"
echo ""

# Helper: extract numeric version from a directory name like "httpx-1.3.21"
extract_version() {
    local dirname
    dirname=$(basename "$1")
    echo "$dirname" | sed -E 's/^[^-]+-//'
}

# Helper: compare two version strings numerically.
version_ge() {
    local higher
    higher=$(printf '%s\n%s\n' "$1" "$2" | sort -V | tail -1)
    [ "$higher" = "$1" ]
}

# Find the best prior version directory for fallback
find_prior_version() {
    local short="$1" dst="$2"
    local src="" src_version=""
    for candidate in "${SCRIPT_DIR}/${short}"-[0-9]*; do
        [ -d "$candidate" ] || continue
        [ "$candidate" = "$dst" ] && continue
        local cand_ver
        cand_ver=$(extract_version "$candidate")
        if [ -z "$src_version" ] || version_ge "$cand_ver" "$src_version"; then
            src="$candidate"
            src_version="$cand_ver"
        fi
    done
    echo "$src"
}

for short in "${REPOS[@]}"; do
    dst="${SCRIPT_DIR}/${short}-${VERSION}"
    [ -d "$dst" ] && log "EXISTS: removing ${dst}" && rm -rf "$dst"

    if [ "$FROM_PRIOR" = false ] && [ -d "${CLEAN_DIR}/${short}" ]; then
        # --- Clean source (preferred) ---
        log "Copying clean/${short} → $(basename "$dst")"
        cp -a "${CLEAN_DIR}/${short}" "$dst"

        # Copy docs_gathered from centralized store
        if [ -d "${DOCS_DIR}/${short}" ] && [ -n "$(ls -A "${DOCS_DIR}/${short}" 2>/dev/null)" ]; then
            mkdir -p "${dst}/docs_gathered"
            cp -a "${DOCS_DIR}/${short}/"* "${dst}/docs_gathered/"
            doc_count=$(ls -1 "${dst}/docs_gathered" | wc -l | tr -d ' ')
            doc_size=$(du -sh "${dst}/docs_gathered" | cut -f1)
            log "  docs_gathered: ${doc_count} files (${doc_size})"
        else
            echo ""
            echo "  *** WARNING: No docs_gathered found for ${short} ***"
            echo "  Expected: ${DOCS_DIR}/${short}/"
            echo "  The playbook will run without gathered documentation,"
            echo "  which significantly reduces artifact quality."
            echo ""
        fi
    else
        # --- Fallback: copy from prior version ---
        if [ "$FROM_PRIOR" = false ]; then
            echo ""
            echo "  *** WARNING: clean/${short} not found — falling back to prior version ***"
            echo "  Run ./create_clean_repos.sh ${short} to create a pristine clone."
            echo ""
        fi

        src=$(find_prior_version "$short" "$dst")
        if [ -z "$src" ]; then
            log "SKIP: ${short} — no clean/ directory and no prior version to copy from"
            continue
        fi

        log "Copying $(basename "$src") → $(basename "$dst") (from prior version)"
        cp -a "$src" "$dst"

        # Clean stale artifacts from prior run
        rm -rf "${dst}/quality" "${dst}/control_prompts" "${dst}/previous_runs"
        rm -f "${dst}/playbook_progress.txt"
        rm -f "${dst}/AGENTS.md"  # Generated by the skill, not part of source

        if [ -d "${dst}/docs_gathered" ] && [ -n "$(ls -A "${dst}/docs_gathered" 2>/dev/null)" ]; then
            doc_count=$(ls -1 "${dst}/docs_gathered" | wc -l | tr -d ' ')
            doc_size=$(du -sh "${dst}/docs_gathered" | cut -f1)
            log "  docs_gathered: ${doc_count} files (${doc_size}) (carried from prior)"
        else
            echo "  *** WARNING: docs_gathered/ is missing or empty ***"
        fi
    fi

    # Install skill files
    mkdir -p "${dst}/.github/skills/references"
    cp "${QPB_DIR}/SKILL.md" "${dst}/.github/skills/SKILL.md"
    cp "${QPB_DIR}/references/"* "${dst}/.github/skills/references/" 2>/dev/null || true
    cp "${QPB_DIR}/LICENSE.txt" "${dst}/.github/skills/LICENSE.txt" 2>/dev/null || true
    cp "${QPB_DIR}/.github/skills/quality_gate/quality_gate.py" "${dst}/.github/skills/quality_gate.py" 2>/dev/null || true

    # v1.5.2: reference_docs/ scaffold. No automated staging — adopters
    # drop plaintext into reference_docs/ (Tier 4 context) and
    # reference_docs/cite/ (citable sources). See README.md "Step 1:
    # Provide documentation" for the contract.
    mkdir -p "${dst}/reference_docs/cite"

    log "  ✓ ${short}-${VERSION} ready"
    echo ""
done

echo "=== Setup complete. Next: python3 ../bin/run_playbook.py ${REPOS[*]} ==="
