# Generated by Quality Playbook v1.5.3 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-28 · Project: quality-playbook

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from bin import classify_project, run_playbook


REPO_ROOT = Path(__file__).resolve().parents[1]


def _extract_index_payload(index_text: str) -> dict:
    start = index_text.index("```json\n") + len("```json\n")
    end = index_text.index("\n```", start)
    return json.loads(index_text[start:end])


class CodeReviewRegressionTests(unittest.TestCase):
    @unittest.expectedFailure
    def test_bug_001_reference_docs_counts_as_docs_present(self) -> None:
        """BUG-001: reference_docs/ should suppress legacy code-only docs warnings."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            (repo / "reference_docs").mkdir()
            (repo / "reference_docs" / "design-notes.md").write_text("# notes\n", encoding="utf-8")
            self.assertTrue(run_playbook.docs_present(repo))

    @unittest.expectedFailure
    def test_bug_002_phase2_gate_enforces_written_contract(self) -> None:
        """BUG-002: long placeholders without the required headings must not pass Phase 2."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            quality = repo / "quality"
            quality.mkdir()
            filler = "\n".join(f"line {i}" for i in range(1, 123))
            (quality / "EXPLORATION.md").write_text(filler, encoding="utf-8")
            gate = run_playbook.check_phase_gate(repo, "2")
            self.assertFalse(gate.ok)

    @unittest.expectedFailure
    def test_bug_003_live_index_preserves_non_code_project_types(self) -> None:
        """BUG-003: live INDEX writers should preserve Skill and Hybrid classifications."""
        for classification in ("Skill", "Hybrid"):
            with self.subTest(classification=classification):
                with tempfile.TemporaryDirectory() as tmp:
                    repo = Path(tmp)
                    (repo / "SKILL.md").write_text("# Skill\n\n" + ("word " * 500), encoding="utf-8")
                    (repo / "bin").mkdir()
                    (repo / "bin" / "tool.py").write_text("print('hello')\n", encoding="utf-8")
                    record = classify_project.classify_project(
                        repo,
                        override=classification,
                        override_rationale="regression fixture",
                    )
                    classify_project.write_classification(repo, record)
                    with mock.patch.object(run_playbook.archive_lib, "_git_head_sha", return_value="deadbeef"):
                        run_playbook.write_live_index_stub(repo, "20260428-131715")
                    stub_payload = _extract_index_payload((repo / "quality" / "INDEX.md").read_text(encoding="utf-8"))
                    self.assertEqual(stub_payload["target_project_type"], classification)
                    run_playbook.write_live_index_final(repo, "20260428-131715", gate_verdict="partial")
                    final_payload = _extract_index_payload((repo / "quality" / "INDEX.md").read_text(encoding="utf-8"))
                    self.assertEqual(final_payload["target_project_type"], classification)

    @unittest.expectedFailure
    def test_bug_004_cleanup_without_pid_files_stays_run_scoped(self) -> None:
        """BUG-004: missing PID files should not trigger workstation-wide pkill fallback."""
        with mock.patch.object(run_playbook, "discover_pid_files", return_value=[]), mock.patch.object(
            run_playbook, "_pkill_fallback"
        ) as fallback:
            run_playbook.kill_recorded_processes()
            fallback.assert_not_called()

    @unittest.expectedFailure
    def test_bug_005_installed_gate_retains_citation_verifier(self) -> None:
        """BUG-005: installed quality_gate.py should keep its Layer-1 verifier dependency."""
        with tempfile.TemporaryDirectory() as tmp:
            install_root = Path(tmp)
            gate_path = install_root / ".github" / "skills" / "quality_gate.py"
            gate_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(REPO_ROOT / ".github" / "skills" / "quality_gate" / "quality_gate.py", gate_path)
            probe = (
                "import importlib.util, pathlib, sys; "
                "path = pathlib.Path(sys.argv[1]); "
                "spec = importlib.util.spec_from_file_location('installed_quality_gate', path); "
                "mod = importlib.util.module_from_spec(spec); "
                "spec.loader.exec_module(mod); "
                "print('present' if mod._CITATION_VERIFIER is not None else 'missing')"
            )
            env = os.environ.copy()
            env["PYTHONPATH"] = str(install_root)
            result = subprocess.run(
                [sys.executable, "-c", probe, str(gate_path)],
                cwd=install_root,
                env=env,
                capture_output=True,
                text=True,
                check=True,
            )
            self.assertEqual(result.stdout.strip(), "present")

    @unittest.expectedFailure
    def test_bug_006_bootstrap_docs_match_live_release_framing(self) -> None:
        """BUG-006: curated bootstrap docs should match the live version and docs terminology."""
        skill_text = (REPO_ROOT / "SKILL.md").read_text(encoding="utf-8")
        live_version = next(
            line.split(":", 1)[1].strip()
            for line in skill_text.splitlines()
            if line.startswith("  version:")
        )
        for path in (
            REPO_ROOT / "docs_gathered" / "01_README_project.md",
            REPO_ROOT / "docs_gathered" / "29_improvement_axes_and_version_history.md",
        ):
            with self.subTest(path=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertIn(live_version, text)
                self.assertIn("reference_docs", text)

    @unittest.expectedFailure
    def test_bug_007_direct_root_and_harness_docs_surfaces_match(self) -> None:
        """BUG-007: direct-root bootstrap should expose the same effective docs set as the harness mirror."""
        expected = sorted(
            path.name
            for path in (REPO_ROOT / "docs_gathered").iterdir()
            if path.is_file() and path.suffix.lower() in {".md", ".txt"} and path.name != "README.md"
        )
        actual = sorted(
            path.relative_to(REPO_ROOT / "reference_docs").as_posix()
            for path in run_playbook._reference_docs_plaintext(REPO_ROOT / "reference_docs")
        )
        self.assertEqual(actual, expected)


if __name__ == "__main__":
    unittest.main()
