# Generated by Quality Playbook v1.5.3 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-28 · Project: quality-playbook

from __future__ import annotations

import importlib.util
import io
import json
import re
import shutil
import sys
import tempfile
import types
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bin import citation_verifier, classify_project, run_playbook


def _extract_index_payload(index_text: str) -> dict:
    match = re.search(r"```json\n(.*?)\n```", index_text, re.DOTALL)
    if not match:
        raise AssertionError("quality/INDEX.md is missing its fenced JSON payload")
    return json.loads(match.group(1))


def _load_module_from_path(module_name: str, path: Path) -> types.ModuleType:
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise AssertionError(f"cannot import module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class RequirementAssertionsMixin:
    def assert_req_001_skill_entry_points_are_synchronized(self) -> None:
        """[Req: inferred — REQ-001] repo-root and installed skill entry points stay aligned."""
        root_skill = REPO_ROOT / "SKILL.md"
        installed_skill = REPO_ROOT / ".github" / "skills" / "SKILL.md"
        self.assertTrue(root_skill.is_file(), "repo-root SKILL.md missing")
        self.assertTrue(installed_skill.is_file(), "installed SKILL.md missing")
        self.assertEqual(root_skill.read_text(encoding="utf-8"), installed_skill.read_text(encoding="utf-8"))

    def assert_req_002_reference_docs_is_authoritative_for_phase1(self) -> None:
        """[Req: inferred — REQ-002] reference_docs drives documentation-availability truth."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            (repo / "reference_docs").mkdir()
            (repo / "reference_docs" / "design-notes.md").write_text("# notes\n", encoding="utf-8")
            self.assertTrue(
                run_playbook.docs_present(repo),
                "a populated reference_docs/ tree should count as docs-present input on a modern install",
            )

    def assert_req_003_phase2_gate_requires_exact_sections(self) -> None:
        """[Req: inferred — REQ-003] malformed long files must not unlock Phase 2."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            quality = repo / "quality"
            quality.mkdir()
            filler = "\n".join(f"line {i}" for i in range(1, 123))
            (quality / "EXPLORATION.md").write_text(filler, encoding="utf-8")
            gate = run_playbook.check_phase_gate(repo, "2")
            self.assertFalse(
                gate.ok,
                "Phase 2 gate should reject a 120+ line placeholder that omits the required headings",
            )

    def assert_req_004_live_index_preserves_project_type(self) -> None:
        """[Req: inferred — REQ-004] live INDEX.md preserves the computed project type."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            (repo / "SKILL.md").write_text("# Skill\n\n" + ("word " * 500), encoding="utf-8")
            (repo / "bin").mkdir()
            (repo / "bin" / "tool.py").write_text("print('hello')\n", encoding="utf-8")
            record = classify_project.classify_project(repo, override="Hybrid", override_rationale="test fixture")
            self.assertEqual(record["classification"], "Hybrid")
            with mock.patch.object(run_playbook.archive_lib, "_git_head_sha", return_value="deadbeef"):
                run_playbook.write_live_index_stub(repo, "20260428-131715")
            payload = _extract_index_payload((repo / "quality" / "INDEX.md").read_text(encoding="utf-8"))
            self.assertEqual(payload["target_project_type"], record["classification"])

    def assert_req_005_cleanup_without_pid_files_stays_run_scoped(self) -> None:
        """[Req: inferred — REQ-005] missing PID files must not widen cleanup scope."""
        with mock.patch.object(run_playbook, "discover_pid_files", return_value=[]), mock.patch.object(
            run_playbook, "_pkill_fallback"
        ) as fallback:
            with redirect_stdout(io.StringIO()):
                run_playbook.kill_recorded_processes()
            fallback.assert_not_called()

    def assert_req_006_installed_gate_retains_citation_verifier(self) -> None:
        """[Req: inferred — REQ-006] installed gate shape keeps Layer-1 verifier support."""
        with tempfile.TemporaryDirectory() as tmp:
            install_root = Path(tmp)
            gate_path = install_root / ".github" / "skills" / "quality_gate.py"
            gate_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(REPO_ROOT / ".github" / "skills" / "quality_gate" / "quality_gate.py", gate_path)
            installed_gate = _load_module_from_path("installed_quality_gate_only", gate_path)
            self.assertIsNotNone(
                installed_gate._CITATION_VERIFIER,
                "installed targets that advertise byte-equal citations must retain citation_verifier support",
            )

    def assert_req_007_bootstrap_docs_match_live_version_and_terms(self) -> None:
        """[Req: inferred — REQ-007] curated bootstrap docs stay current with live release framing."""
        skill_text = (REPO_ROOT / "SKILL.md").read_text(encoding="utf-8")
        version_match = re.search(r"^  version:\s*([0-9.]+)\s*$", skill_text, re.MULTILINE)
        self.assertIsNotNone(version_match, "could not read live SKILL.md version")
        live_version = version_match.group(1)
        bootstrap_docs = [
            REPO_ROOT / "docs_gathered" / "01_README_project.md",
            REPO_ROOT / "docs_gathered" / "29_improvement_axes_and_version_history.md",
        ]
        for path in bootstrap_docs:
            text = path.read_text(encoding="utf-8")
            self.assertIn(live_version, text, f"{path.name} should describe the live release version")
            self.assertIn("reference_docs", text, f"{path.name} should use the modern documentation-path terminology")

    def assert_req_008_direct_and_harness_bootstrap_share_docs_surface(self) -> None:
        """[Req: inferred — REQ-008] direct-root and harness installs expose the same docs surface."""
        docs_gathered_files = sorted(
            path.name
            for path in (REPO_ROOT / "docs_gathered").iterdir()
            if path.is_file() and not path.name.startswith(".")
        )
        reference_docs_files = sorted(
            path.relative_to(REPO_ROOT / "reference_docs").as_posix()
            for path in run_playbook._reference_docs_plaintext(REPO_ROOT / "reference_docs")
        )
        self.assertEqual(
            docs_gathered_files,
            reference_docs_files,
            "repo-root self-audit should expose the same effective docs surface that the harness mirrors into reference_docs/",
        )


class SpecRequirementTests(RequirementAssertionsMixin, unittest.TestCase):
    def test_req_001_skill_entry_points_are_synchronized(self) -> None:
        self.assert_req_001_skill_entry_points_are_synchronized()

    def test_req_002_reference_docs_is_authoritative_for_phase1(self) -> None:
        self.assert_req_002_reference_docs_is_authoritative_for_phase1()

    def test_req_003_phase2_gate_requires_exact_sections(self) -> None:
        self.assert_req_003_phase2_gate_requires_exact_sections()

    def test_req_004_live_index_preserves_project_type(self) -> None:
        self.assert_req_004_live_index_preserves_project_type()

    def test_req_005_cleanup_without_pid_files_stays_run_scoped(self) -> None:
        self.assert_req_005_cleanup_without_pid_files_stays_run_scoped()

    def test_req_006_installed_gate_retains_citation_verifier(self) -> None:
        self.assert_req_006_installed_gate_retains_citation_verifier()

    def test_req_007_bootstrap_docs_match_live_version_and_terms(self) -> None:
        self.assert_req_007_bootstrap_docs_match_live_version_and_terms()

    def test_req_008_direct_and_harness_bootstrap_share_docs_surface(self) -> None:
        self.assert_req_008_direct_and_harness_bootstrap_share_docs_surface()


class FitnessScenarioTests(RequirementAssertionsMixin, unittest.TestCase):
    def test_scenario_1_modern_docs_installs_are_not_warned_as_code_only(self) -> None:
        self.assert_req_002_reference_docs_is_authoritative_for_phase1()

    def test_scenario_2_malformed_exploration_does_not_unlock_phase2(self) -> None:
        self.assert_req_003_phase2_gate_requires_exact_sections()

    def test_scenario_3_hybrid_targets_do_not_collapse_to_code(self) -> None:
        self.assert_req_004_live_index_preserves_project_type()

    def test_scenario_4_cleanup_without_pid_files_remains_safe(self) -> None:
        self.assert_req_005_cleanup_without_pid_files_stays_run_scoped()

    def test_scenario_5_installed_citation_workflows_keep_byte_equality(self) -> None:
        self.assert_req_006_installed_gate_retains_citation_verifier()

    def test_scenario_6_bootstrap_docs_describe_the_live_release(self) -> None:
        self.assert_req_007_bootstrap_docs_match_live_version_and_terms()

    def test_scenario_7_direct_and_harness_bootstrap_see_the_same_docs(self) -> None:
        self.assert_req_008_direct_and_harness_bootstrap_share_docs_surface()

    def test_scenario_8_skill_entry_point_fallbacks_are_equivalent(self) -> None:
        self.assert_req_001_skill_entry_points_are_synchronized()


class BoundaryAndEdgeCaseTests(unittest.TestCase):
    def test_boundary_1_reference_docs_plaintext_helper_ignores_hidden_and_non_plaintext(self) -> None:
        """[Req: inferred — from _reference_docs_plaintext() boundary handling] only plaintext docs count."""
        with tempfile.TemporaryDirectory() as tmp:
            reference_docs = Path(tmp) / "reference_docs"
            (reference_docs / "cite").mkdir(parents=True)
            (reference_docs / "README.md").write_text("ignored", encoding="utf-8")
            (reference_docs / "design.md").write_text("# Design", encoding="utf-8")
            (reference_docs / "cite" / "spec.txt").write_text("spec", encoding="utf-8")
            (reference_docs / ".secret").write_text("ignored", encoding="utf-8")
            (reference_docs / "diagram.pdf").write_text("%PDF", encoding="utf-8")
            found = [path.relative_to(reference_docs).as_posix() for path in run_playbook._reference_docs_plaintext(reference_docs)]
            self.assertEqual(found, ["cite/spec.txt", "design.md"])

    def test_boundary_2_citation_verifier_rejects_invalid_utf8(self) -> None:
        """[Req: inferred — from citation_verifier strict decode] malformed bytes are rejected."""
        with self.assertRaises(citation_verifier.CitationResolutionError):
            citation_verifier.extract_excerpt(b"\xff\xfe\xfd", ".txt", None, 1)

    def test_boundary_3_citation_verifier_rejects_blank_anchor(self) -> None:
        """[Req: inferred — from citation_verifier blank-anchor guard] blank citation anchors are illegal."""
        with self.assertRaises(citation_verifier.CitationResolutionError):
            citation_verifier.extract_excerpt(b"alpha\n\nomega\n", ".txt", None, 2)

    def test_boundary_4_phase2_gate_contract_is_not_length_only(self) -> None:
        """[Req: inferred — from check_phase_gate() contract] long placeholders do not qualify."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            quality = repo / "quality"
            quality.mkdir()
            content = "## Open Exploration Findings\n" + "\n".join(f"filler {i}" for i in range(1, 130))
            (quality / "EXPLORATION.md").write_text(content, encoding="utf-8")
            gate = run_playbook.check_phase_gate(repo, "2")
            self.assertFalse(gate.ok)

    def test_boundary_5_project_type_closed_set_survives_into_index_writers(self) -> None:
        """[Req: inferred — from project-type whitelist] live index writers preserve all allowed values."""
        self.assertEqual(set(classify_project.VALID_CLASSIFICATIONS), {"Code", "Skill", "Hybrid"})
        run_playbook_text = (REPO_ROOT / "bin" / "run_playbook.py").read_text(encoding="utf-8")
        self.assertIn('"target_project_type": "Hybrid"', run_playbook_text)
        self.assertIn('target_project_type="Hybrid"', run_playbook_text)


if __name__ == "__main__":
    unittest.main()
