#!/bin/bash
# Generated by Quality Playbook v1.4.0 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-15 · Project: quality-playbook (bootstrap self-audit)
#
# Functional tests for the Quality Playbook specification and validation script.
# These tests verify behavioral requirements derived from SKILL.md and quality_gate.sh.
#
# Usage: bash quality/test_functional.sh
#   or:  bash quality/test_functional.sh <test_name>

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SKILL="${PROJECT_ROOT}/SKILL.md"
GATE="${PROJECT_ROOT}/quality_gate.sh"
PASS=0
FAIL=0
SKIP=0
RUN_FILTER="${1:-}"

pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; }
skip() { SKIP=$((SKIP + 1)); echo "  SKIP: $1"; }

should_run() {
    [ -z "$RUN_FILTER" ] || [ "$RUN_FILTER" = "$1" ]
}

# ============================================================================
# Group 1: Spec Requirements
# ============================================================================

echo "=== Spec Requirements ==="

# [Req: formal — REQ-001] tdd-results.json summary key consistency
test_req001_summary_key_consistency() {
    echo "[REQ-001] Summary key 'verified' vs 'tdd_verified' consistency"
    local tdd_verified_count verified_count
    # Count occurrences of tdd_verified in JSON example blocks
    tdd_verified_count=$(grep -c '"tdd_verified"' "$SKILL" 2>/dev/null || echo 0)
    verified_count=$(grep -c '"verified"' "$SKILL" 2>/dev/null || echo 0)

    # The normative text at line 1394 says 'verified' is canonical.
    # Example 1 uses 'tdd_verified' — this is the bug.
    if [ "$tdd_verified_count" -gt 0 ]; then
        fail "SKILL.md contains $tdd_verified_count occurrence(s) of 'tdd_verified' — should be 'verified' per normative text (line 1394)"
    else
        pass "No 'tdd_verified' in SKILL.md — consistent with normative text"
    fi
}

# [Req: formal — REQ-001] quality_gate.sh validates total and verified summary keys
test_req001_gate_validates_summary_keys() {
    echo "[REQ-001] quality_gate.sh validates 'total' and 'verified' summary keys"
    local checks_total checks_verified
    checks_total=$(grep -c '"total"' "$GATE" 2>/dev/null || echo 0)
    checks_verified=$(grep -cE '"verified"' "$GATE" 2>/dev/null || echo 0)

    # The gate should check for 'total' and 'verified' in the summary validation
    # Currently it only checks confirmed_open, red_failed, green_failed
    if grep -q 'for skey in.*total' "$GATE" 2>/dev/null; then
        pass "quality_gate.sh checks for 'total' summary key"
    else
        fail "quality_gate.sh does not check for 'total' summary key"
    fi
    if grep -q 'for skey in.*verified' "$GATE" 2>/dev/null; then
        pass "quality_gate.sh checks for 'verified' summary key"
    else
        fail "quality_gate.sh does not check for 'verified' summary key"
    fi
}

# [Req: formal — REQ-002] Phase numbering consistency
test_req002_phase_numbering() {
    echo "[REQ-002] Phase 7 in plan overview"
    local plan_overview_has_phase7
    # Plan overview is lines 12-31. Check if Phase 7 is mentioned there.
    plan_overview_has_phase7=$(sed -n '12,31p' "$SKILL" | grep -ci 'phase 7' | head -1 || echo 0)
    local body_has_phase7
    body_has_phase7=$(grep -c '## Phase 7' "$SKILL" 2>/dev/null || echo 0)

    if [ "$body_has_phase7" -gt 0 ] && [ "$plan_overview_has_phase7" -eq 0 ]; then
        fail "Phase 7 exists in SKILL.md body but NOT in plan overview (lines 12-31)"
    elif [ "$body_has_phase7" -gt 0 ] && [ "$plan_overview_has_phase7" -gt 0 ]; then
        pass "Phase 7 in body and plan overview are consistent"
    else
        pass "No Phase 7 in body — no inconsistency"
    fi
}

# [Req: formal — REQ-002] Convergence check reference to Phase 7
test_req002_convergence_phase7_ref() {
    echo "[REQ-002] Convergence check 'skip to Phase 7' reference"
    if grep -qi 'skip to Phase 7' "$SKILL" 2>/dev/null; then
        local plan_has_7
        plan_has_7=$(sed -n '12,31p' "$SKILL" | grep -ci 'phase 7' | head -1 || echo 0)
        if [ "$plan_has_7" -eq 0 ]; then
            fail "'skip to Phase 7' reference exists but Phase 7 not in plan overview"
        else
            pass "'skip to Phase 7' reference is consistent with plan overview"
        fi
    else
        pass "No 'skip to Phase 7' reference found"
    fi
}

# [Req: formal — REQ-003] Hardcoded .github/skills/references/ paths
test_req003_hardcoded_paths() {
    echo "[REQ-003] Reference paths must not be hardcoded to .github/skills/references/"
    local hardcoded_count
    hardcoded_count=$(grep -c '\.github/skills/references/' "$SKILL" 2>/dev/null || echo 0)
    if [ "$hardcoded_count" -gt 0 ]; then
        fail "SKILL.md has $hardcoded_count hardcoded .github/skills/references/ path(s) — breaks Claude Code installations"
    else
        pass "No hardcoded .github/skills/references/ paths in SKILL.md"
    fi
}

# [Req: formal — REQ-004] quality_gate.sh validates TDD log status tags
test_req004_tdd_log_status_tags() {
    echo "[REQ-004] quality_gate.sh validates TDD log status tags (RED/GREEN/NOT_RUN/ERROR)"
    # SKILL.md line 1137 claims the gate checks for status tag presence
    local claim_exists gate_reads_tag
    claim_exists=$(grep -c 'quality_gate.sh will check for its presence' "$SKILL" 2>/dev/null || echo 0)
    # Check if quality_gate.sh actually reads the first line of log files
    gate_reads_tag=$(grep -cE 'head -1|sed -n 1p|read.*log|RED|GREEN|NOT_RUN|ERROR' "$GATE" 2>/dev/null || echo 0)

    if [ "$claim_exists" -gt 0 ] && [ "$gate_reads_tag" -eq 0 ]; then
        fail "SKILL.md claims gate checks TDD log status tags, but quality_gate.sh only checks file existence"
    elif [ "$claim_exists" -gt 0 ] && [ "$gate_reads_tag" -gt 0 ]; then
        pass "SKILL.md claim and quality_gate.sh validation are consistent"
    else
        pass "No inconsistency (claim not found or gate validates)"
    fi
}

# [Req: formal — REQ-005] File existence checks cover required artifacts
test_req005_file_existence_contracts() {
    echo "[REQ-005] quality_gate.sh checks for CONTRACTS.md"
    if grep -q 'CONTRACTS.md' "$GATE" 2>/dev/null; then
        pass "quality_gate.sh checks for CONTRACTS.md"
    else
        fail "quality_gate.sh does NOT check for CONTRACTS.md (marked Required in artifact table)"
    fi
}

test_req005_file_existence_exploration() {
    echo "[REQ-005] quality_gate.sh checks for EXPLORATION.md"
    if grep -q 'EXPLORATION.md' "$GATE" 2>/dev/null; then
        pass "quality_gate.sh checks for EXPLORATION.md"
    else
        fail "quality_gate.sh does NOT check for EXPLORATION.md"
    fi
}

test_req005_file_existence_run_protocols() {
    echo "[REQ-005] quality_gate.sh checks for RUN_*.md protocol files"
    local missing=0
    for f in RUN_CODE_REVIEW.md RUN_INTEGRATION_TESTS.md RUN_SPEC_AUDIT.md RUN_TDD_TESTS.md; do
        if ! grep -q "$f" "$GATE" 2>/dev/null; then
            fail "quality_gate.sh does NOT check for $f (marked Required)"
            missing=$((missing + 1))
        fi
    done
    [ "$missing" -eq 0 ] && pass "quality_gate.sh checks for all RUN_*.md files"
}

# [Req: formal — REQ-006] DEVELOPMENT_CONTEXT.md Phase 3 mislabel
test_req006_dev_context_phase_label() {
    echo "[REQ-006] DEVELOPMENT_CONTEXT.md labels verification.md correctly as Phase 6"
    local dev_ctx="${PROJECT_ROOT}/ai_context/DEVELOPMENT_CONTEXT.md"
    if [ -f "$dev_ctx" ]; then
        if grep -q 'verification.md.*Phase 3' "$dev_ctx" 2>/dev/null; then
            fail "DEVELOPMENT_CONTEXT.md labels verification.md as Phase 3 (should be Phase 6)"
        else
            pass "DEVELOPMENT_CONTEXT.md does not mislabel verification.md as Phase 3"
        fi
    else
        skip "DEVELOPMENT_CONTEXT.md not found"
    fi
}

# [Req: formal — REQ-007] AGENTS.md Claude Code installation path
test_req007_agents_claude_path() {
    echo "[REQ-007] AGENTS.md includes Claude Code installation path"
    local agents_md="${PROJECT_ROOT}/AGENTS.md"
    if [ -f "$agents_md" ]; then
        if grep -q '\.claude/skills' "$agents_md" 2>/dev/null; then
            pass "AGENTS.md includes .claude/skills path"
        else
            fail "AGENTS.md does NOT include .claude/skills path (only shows Copilot installation)"
        fi
    else
        skip "AGENTS.md not found"
    fi
}

# [Req: formal — REQ-008] Artifact table Created In for verify.sh
test_req008_verify_created_in() {
    echo "[REQ-008] Artifact table 'Created In' for verify.sh"
    # Check whether the artifact table says verify.sh is Phase 5
    # AND whether the instructions say to create it in Phase 2
    local table_phase
    table_phase=$(grep -A1 'verify.sh\|mechanical.*verify' "$SKILL" 2>/dev/null | grep -oE 'Phase [0-9]+' | head -1 || echo "")
    local instruction_phase
    instruction_phase=$(grep -B5 'verify.sh' "$SKILL" 2>/dev/null | grep -oE 'Phase [0-9]+[ab]*' | head -1 || echo "")

    if echo "$table_phase" | grep -q 'Phase 5' && echo "$instruction_phase" | grep -qi 'Phase 2'; then
        fail "Artifact table says verify.sh is 'Phase 5' but instructions create it in Phase 2"
    else
        pass "verify.sh Created In column is consistent with instructions (or cannot determine)"
    fi
}

# [Req: formal — REQ-011] TOOLKIT.md installation paths
test_req011_toolkit_both_paths() {
    echo "[REQ-011] TOOLKIT.md documents both installation paths"
    local toolkit="${PROJECT_ROOT}/ai_context/TOOLKIT.md"
    if [ -f "$toolkit" ]; then
        local has_github has_claude
        has_github=$(grep -c '.github/skills' "$toolkit" 2>/dev/null || echo 0)
        has_claude=$(grep -c '.claude/skills' "$toolkit" 2>/dev/null || echo 0)
        if [ "$has_github" -gt 0 ] && [ "$has_claude" -gt 0 ]; then
            pass "TOOLKIT.md shows both .github/skills/ and .claude/skills/ paths"
        elif [ "$has_github" -gt 0 ] && [ "$has_claude" -eq 0 ]; then
            fail "TOOLKIT.md only shows .github/skills/ path — missing Claude Code installation"
        else
            fail "TOOLKIT.md missing expected installation paths"
        fi
    else
        skip "TOOLKIT.md not found"
    fi
}

# [Req: formal — REQ-012] Per-bug field classification
test_req012_perbug_field_classification() {
    echo "[REQ-012] SKILL.md classifies additional per-bug fields as required or optional"
    # Check if SKILL.md explicitly marks the additional fields (regression_patch, fix_patch,
    # patch_gate_passed, junit_red, junit_green, junit_available, notes)
    local has_classification
    has_classification=$(grep -cE '(optional|required).*per-bug|per-bug.*(optional|required)' "$SKILL" 2>/dev/null || echo 0)
    # The normative text at line 1392 lists 7 required fields.
    # Example 2 has 14 fields. The extra 7 are not classified.
    local extra_fields_documented
    extra_fields_documented=$(grep -c 'regression_patch.*optional\|notes.*optional\|junit_.*optional' "$SKILL" 2>/dev/null || echo 0)
    if [ "$extra_fields_documented" -gt 0 ]; then
        pass "Additional per-bug fields are classified in SKILL.md"
    else
        fail "Additional per-bug fields in Example 2 are not classified as required or optional"
    fi
}

# ============================================================================
# Group 2: Fitness Scenarios
# ============================================================================

echo ""
echo "=== Fitness Scenarios ==="

# Scenario 1: JSON schema template contradiction
test_scenario1_json_schema_contradiction() {
    echo "[Scenario 1] No contradictory JSON summary keys in SKILL.md"
    local tdd_verified_in_json
    # Check specifically in JSON example blocks for tdd_verified
    tdd_verified_in_json=$(grep -c '"tdd_verified"' "$SKILL" 2>/dev/null || echo 0)
    if [ "$tdd_verified_in_json" -gt 0 ]; then
        fail "SKILL.md JSON examples contain 'tdd_verified' — contradicts normative 'verified' (line 1394)"
    else
        pass "All JSON examples use consistent summary keys"
    fi
}

# Scenario 2: Hardcoded paths break Claude Code
test_scenario2_hardcoded_paths() {
    echo "[Scenario 2] No hardcoded .github/skills/references/ in Phase headers"
    local phase_header_hardcoded
    phase_header_hardcoded=$(grep -A5 'Required references for this phase' "$SKILL" 2>/dev/null | grep -c '\.github/skills/references/' || echo 0)
    if [ "$phase_header_hardcoded" -gt 0 ]; then
        fail "$phase_header_hardcoded Phase header(s) use hardcoded .github/skills/references/ paths"
    else
        pass "Phase headers do not use hardcoded paths"
    fi
}

# Scenario 3: Gate under-validation
test_scenario3_gate_undervalidation() {
    echo "[Scenario 3] quality_gate.sh checks all Required artifacts"
    # Count Required artifacts from SKILL.md artifact table (approximation)
    local required_in_table checked_by_gate
    required_in_table=0
    checked_by_gate=0
    for artifact in QUALITY.md REQUIREMENTS.md CONTRACTS.md COVERAGE_MATRIX.md COMPLETENESS_REPORT.md PROGRESS.md BUGS.md; do
        required_in_table=$((required_in_table + 1))
        if grep -q "\"$artifact\"" "$GATE" 2>/dev/null || grep -q "'$artifact'" "$GATE" 2>/dev/null || grep -q "$artifact" "$GATE" 2>/dev/null; then
            checked_by_gate=$((checked_by_gate + 1))
        fi
    done
    if [ "$checked_by_gate" -lt "$required_in_table" ]; then
        fail "Gate checks $checked_by_gate of $required_in_table required core artifacts"
    else
        pass "Gate checks all $required_in_table required core artifacts"
    fi
}

# Scenario 4: Phase 7 unreachable
test_scenario4_phase7_unreachable() {
    echo "[Scenario 4] Phase 7 reachability"
    local phase7_defined plan_overview_mentions end_of_6_mentions
    phase7_defined=$(grep -c '## Phase 7' "$SKILL" 2>/dev/null || echo 0)
    plan_overview_mentions=$(sed -n '12,31p' "$SKILL" | grep -ci 'phase 7' | head -1 || echo 0)
    end_of_6_mentions=$(grep -A20 'Phase 6 Complete' "$SKILL" 2>/dev/null | grep -ci 'phase 7' | head -1 || echo 0)

    if [ "$phase7_defined" -gt 0 ] && [ "$plan_overview_mentions" -eq 0 ] && [ "$end_of_6_mentions" -eq 0 ]; then
        fail "Phase 7 defined but unreachable — not in plan overview or end-of-Phase-6 message"
    else
        pass "Phase 7 reachability is consistent"
    fi
}

# Scenario 5: AGENTS.md missing Claude Code path
test_scenario5_agents_claude_path() {
    echo "[Scenario 5] AGENTS.md Claude Code installation"
    test_req007_agents_claude_path  # Reuses the REQ-007 test
}

# Scenario 6: Artifact table phase contradiction
test_scenario6_artifact_table_phase() {
    echo "[Scenario 6] verify.sh phase assignment"
    test_req008_verify_created_in  # Reuses the REQ-008 test
}

# ============================================================================
# Group 3: Boundaries and Edge Cases
# ============================================================================

echo ""
echo "=== Boundaries and Edge Cases ==="

# [Req: inferred — quality_gate.sh glob safety]
test_boundary_glob_empty_match() {
    echo "[REQ-009] Glob patterns handle empty match"
    # Check if the writeup loop uses a glob guard (nullglob, [[ -f ]], etc.)
    local has_file_guard
    has_file_guard=$(grep -A2 'for wf in.*writeups.*BUG' "$GATE" 2>/dev/null | grep -c '\[ -f' || echo 0)
    if [ "$has_file_guard" -gt 0 ]; then
        pass "Writeup glob loop has file existence guard"
    else
        # The guard exists (line 508: [ -f "$wf" ] || continue) but the glob
        # still expands to the literal pattern. Check if the guard catches it.
        local has_continue
        has_continue=$(grep -A3 'for wf in.*writeups.*BUG' "$GATE" 2>/dev/null | grep -c 'continue' || echo 0)
        if [ "$has_continue" -gt 0 ]; then
            pass "Writeup glob loop has continue guard for non-matching globs"
        else
            fail "Writeup glob loop has no guard against empty glob expansion"
        fi
    fi
}

# [Req: inferred — quality_gate.sh set -e not set]
test_boundary_set_e() {
    echo "[Edge] quality_gate.sh uses set -e"
    if grep -q 'set -e' "$GATE" 2>/dev/null; then
        pass "quality_gate.sh has set -e"
    else
        # This is intentional — the script uses manual FAIL counting instead of set -e.
        # But it means individual command failures don't abort the script.
        pass "quality_gate.sh deliberately omits set -e (uses FAIL counter pattern)"
    fi
}

# [Req: inferred — version detection]
test_boundary_version_detection() {
    echo "[Edge] quality_gate.sh version detection tries multiple SKILL.md locations"
    local location_count
    location_count=$(grep -c 'SKILL.md' "$GATE" 2>/dev/null | head -1 || echo 0)
    if [ "$location_count" -ge 3 ]; then
        pass "Version detection checks 3+ SKILL.md locations"
    else
        fail "Version detection checks fewer than 3 SKILL.md locations"
    fi
}

# [Req: inferred — orchestrator path consistency]
test_boundary_orchestrator_paths() {
    echo "[Edge] Both orchestrators check for Claude Code installation path"
    local claude_agent="${PROJECT_ROOT}/agents/quality-playbook-claude.agent.md"
    local general_agent="${PROJECT_ROOT}/agents/quality-playbook.agent.md"
    local claude_check=0 general_check=0
    if [ -f "$claude_agent" ] && grep -q '\.claude/skills' "$claude_agent" 2>/dev/null; then
        claude_check=1
    fi
    if [ -f "$general_agent" ] && grep -q '\.claude/skills' "$general_agent" 2>/dev/null; then
        general_check=1
    fi
    if [ "$claude_check" -eq 1 ] && [ "$general_check" -eq 1 ]; then
        pass "Both orchestrators check for .claude/skills/ path"
    else
        fail "Not all orchestrators check for .claude/skills/ path (claude=$claude_check, general=$general_check)"
    fi
}

# [Req: inferred — JSON helper correctness]
test_boundary_json_helpers() {
    echo "[Edge] json_has_key uses grep (not JSON parser)"
    if grep -q 'grep.*"${key}"' "$GATE" 2>/dev/null; then
        # This is by design — the project uses grep-based JSON parsing.
        # But it means nested key names could false-match.
        pass "json_has_key uses grep (design choice — no JSON parser dependency)"
    else
        skip "Cannot determine json_has_key implementation"
    fi
}

# ============================================================================
# Run all tests
# ============================================================================

echo ""
echo "=== Running Tests ==="
echo ""

# Spec Requirements
should_run "test_req001_summary_key_consistency" && test_req001_summary_key_consistency
should_run "test_req001_gate_validates_summary_keys" && test_req001_gate_validates_summary_keys
should_run "test_req002_phase_numbering" && test_req002_phase_numbering
should_run "test_req002_convergence_phase7_ref" && test_req002_convergence_phase7_ref
should_run "test_req003_hardcoded_paths" && test_req003_hardcoded_paths
should_run "test_req004_tdd_log_status_tags" && test_req004_tdd_log_status_tags
should_run "test_req005_file_existence_contracts" && test_req005_file_existence_contracts
should_run "test_req005_file_existence_exploration" && test_req005_file_existence_exploration
should_run "test_req005_file_existence_run_protocols" && test_req005_file_existence_run_protocols
should_run "test_req006_dev_context_phase_label" && test_req006_dev_context_phase_label
should_run "test_req007_agents_claude_path" && test_req007_agents_claude_path
should_run "test_req008_verify_created_in" && test_req008_verify_created_in
should_run "test_req011_toolkit_both_paths" && test_req011_toolkit_both_paths
should_run "test_req012_perbug_field_classification" && test_req012_perbug_field_classification

# Fitness Scenarios
should_run "test_scenario1_json_schema_contradiction" && test_scenario1_json_schema_contradiction
should_run "test_scenario2_hardcoded_paths" && test_scenario2_hardcoded_paths
should_run "test_scenario3_gate_undervalidation" && test_scenario3_gate_undervalidation
should_run "test_scenario4_phase7_unreachable" && test_scenario4_phase7_unreachable
should_run "test_scenario5_agents_claude_path" && test_scenario5_agents_claude_path
should_run "test_scenario6_artifact_table_phase" && test_scenario6_artifact_table_phase

# Boundaries
should_run "test_boundary_glob_empty_match" && test_boundary_glob_empty_match
should_run "test_boundary_set_e" && test_boundary_set_e
should_run "test_boundary_version_detection" && test_boundary_version_detection
should_run "test_boundary_orchestrator_paths" && test_boundary_orchestrator_paths
should_run "test_boundary_json_helpers" && test_boundary_json_helpers

echo ""
echo "==========================================="
echo "Results: ${PASS} PASS, ${FAIL} FAIL, ${SKIP} SKIP"
echo "Total:   $((PASS + FAIL + SKIP)) tests"
if [ "$FAIL" -gt 0 ]; then
    echo "STATUS: SOME TESTS FAILED"
    exit 1
else
    echo "STATUS: ALL TESTS PASSED"
    exit 0
fi
