#!/bin/bash
# Generated by Quality Playbook v1.4.0 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-15 · Project: quality-playbook (QFB-bootstrap)
#
# Regression tests for confirmed bugs. Each test is marked as expected-to-fail
# (skip guard) until the corresponding fix patch is applied.
#
# Usage: bash quality/test_regression.sh
#   Runs all regression tests. Exit 0 if all expected failures occur.
#   Tests can be run individually by setting RUN_BUG=NNN environment variable.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
GATE="${REPO_DIR}/quality_gate.sh"
PASS=0
FAIL=0
XFAIL=0
TOTAL=0

pass()  { echo "  PASS: $1"; PASS=$((PASS + 1)); TOTAL=$((TOTAL + 1)); }
fail()  { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); TOTAL=$((TOTAL + 1)); }
xfail() { echo "  XFAIL: $1"; XFAIL=$((XFAIL + 1)); TOTAL=$((TOTAL + 1)); }

setup_test_dir() {
    local dir
    dir=$(mktemp -d)
    mkdir -p "${dir}/quality/code_reviews" "${dir}/quality/spec_audits"
    echo "$dir"
}

create_passing_artifacts() {
    local dir="$1"
    local q="${dir}/quality"
    # Create all FAIL-checked artifacts with proper content
    echo -e "# BUGS\nNo confirmed bugs. 0 confirmed bugs." > "${q}/BUGS.md"
    echo -e "# REQUIREMENTS\n\n## Use Cases\n\n### UC-01: Test\n### UC-02: Test\n### UC-03: Test\n### UC-04: Test\n### UC-05: Test" > "${q}/REQUIREMENTS.md"
    echo "# QUALITY" > "${q}/QUALITY.md"
    echo -e "# PROGRESS\nSkill version: 1.4.0\n\n## Terminal Gate Verification" > "${q}/PROGRESS.md"
    echo "# COVERAGE" > "${q}/COVERAGE_MATRIX.md"
    echo "# COMPLETENESS" > "${q}/COMPLETENESS_REPORT.md"
    echo "# Review" > "${q}/code_reviews/review.md"
    echo "# Triage" > "${q}/spec_audits/triage.md"
    echo "# Auditor" > "${q}/spec_audits/auditor-1.md"
    echo '#!/bin/bash' > "${q}/spec_audits/triage_probes.sh"
    # Create WARN-checked artifacts (so they don't interfere)
    echo "# CONTRACTS" > "${q}/CONTRACTS.md"
    echo "# RUN_CODE_REVIEW" > "${q}/RUN_CODE_REVIEW.md"
    echo "# RUN_SPEC_AUDIT" > "${q}/RUN_SPEC_AUDIT.md"
    echo "# RUN_INTEGRATION_TESTS" > "${q}/RUN_INTEGRATION_TESTS.md"
    echo "# RUN_TDD_TESTS" > "${q}/RUN_TDD_TESTS.md"
    echo "#!/bin/bash" > "${q}/test_functional.sh"
    # Copy SKILL.md for version detection
    cp "${REPO_DIR}/SKILL.md" "${dir}/"
}

cleanup() {
    [ -n "${1:-}" ] && rm -rf "$1"
}

# ──────────────────────────────────────────────────────────────────────
# BUG-001: Required artifacts downgraded to WARN
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-001-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_001_required_artifacts_warn_severity() {
    # BUG-001: quality_gate.sh uses warn() for 6 required artifacts
    # [Spec basis: SKILL.md lines 83-85, artifact contract table lines 86-115]
    # Expected: gate exits 1 when CONTRACTS.md is missing (required artifact)
    # Actual (bug): gate exits 0 because missing CONTRACTS.md only triggers warn()
    local dir
    dir=$(setup_test_dir)
    create_passing_artifacts "$dir"
    # Remove CONTRACTS.md -- a Required: Yes artifact
    rm "${dir}/quality/CONTRACTS.md"

    local exit_code=0
    bash "${GATE}" "$dir" > /dev/null 2>&1 || exit_code=$?

    if [ "$exit_code" -eq 1 ]; then
        pass "BUG-001: Gate correctly fails when CONTRACTS.md is missing"
    else
        # BUG CONFIRMED: gate passes despite missing required artifact
        xfail "BUG-001: Gate exits 0 despite missing CONTRACTS.md (Required: Yes in SKILL.md)"
    fi
    cleanup "$dir"
}

test_bug_001_all_warn_artifacts_missing() {
    # BUG-001: All 6 WARN-checked artifacts missing, gate still passes
    local dir
    dir=$(setup_test_dir)
    create_passing_artifacts "$dir"
    # Remove all WARN-checked artifacts
    rm -f "${dir}/quality/CONTRACTS.md"
    rm -f "${dir}/quality/RUN_CODE_REVIEW.md"
    rm -f "${dir}/quality/RUN_SPEC_AUDIT.md"
    rm -f "${dir}/quality/RUN_INTEGRATION_TESTS.md"
    rm -f "${dir}/quality/RUN_TDD_TESTS.md"
    rm -f "${dir}/quality/test_functional.sh"

    local exit_code=0
    bash "${GATE}" "$dir" > /dev/null 2>&1 || exit_code=$?

    if [ "$exit_code" -eq 1 ]; then
        pass "BUG-001: Gate correctly fails when all 6 required artifacts missing"
    else
        xfail "BUG-001: Gate exits 0 despite 6 required artifacts missing"
    fi
    cleanup "$dir"
}

# ──────────────────────────────────────────────────────────────────────
# BUG-002: test_functional detection misses alternative names
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-002-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_002_functional_test_java_name() {
    # BUG-002: FunctionalTest.java not detected by quality_gate.sh
    # [Spec basis: SKILL.md line 69]
    local dir
    dir=$(setup_test_dir)
    create_passing_artifacts "$dir"
    rm "${dir}/quality/test_functional.sh"
    echo "public class FunctionalTest {}" > "${dir}/quality/FunctionalTest.java"

    local output
    output=$(bash "${GATE}" "$dir" 2>&1 || true)

    if echo "$output" | grep -qi "WARN.*test_functional.*missing"; then
        xfail "BUG-002: Gate misses FunctionalTest.java (warns about test_functional.* missing)"
    else
        pass "BUG-002: Gate detects FunctionalTest.java"
    fi
    cleanup "$dir"
}

test_bug_002_functional_test_ts_name() {
    # BUG-002: functional.test.ts not detected
    local dir
    dir=$(setup_test_dir)
    create_passing_artifacts "$dir"
    rm "${dir}/quality/test_functional.sh"
    echo "// test" > "${dir}/quality/functional.test.ts"

    local output
    output=$(bash "${GATE}" "$dir" 2>&1 || true)

    if echo "$output" | grep -qi "WARN.*test_functional.*missing"; then
        xfail "BUG-002: Gate misses functional.test.ts"
    else
        pass "BUG-002: Gate detects functional.test.ts"
    fi
    cleanup "$dir"
}

# ──────────────────────────────────────────────────────────────────────
# BUG-003: eval injection with user-supplied paths
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-003-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_003_eval_usage_in_gate() {
    # BUG-003: quality_gate.sh uses eval with user-supplied paths
    # [Spec basis: quality_gate.sh lines 439-448]
    # Verify eval is used with repo_dir variable (source-inspection test)
    local eval_with_repo_dir
    eval_with_repo_dir=$(grep -c 'eval.*\${repo_dir}\|eval.*repo_dir' "${GATE}" 2>/dev/null || echo 0)

    if [ "$eval_with_repo_dir" -gt 0 ]; then
        xfail "BUG-003: quality_gate.sh uses eval with repo_dir (${eval_with_repo_dir} occurrences)"
    else
        pass "BUG-003: quality_gate.sh does not use eval with user-supplied paths"
    fi
}

# ──────────────────────────────────────────────────────────────────────
# BUG-004: review_protocols.md Phase 6 numbering error
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-004-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_004_phase_numbering() {
    # BUG-004: review_protocols.md has "Phase 6: Results" instead of "Phase 3: Results"
    # [Spec basis: references/review_protocols.md line 376]
    if grep -q "### Phase 6: Results" "${REPO_DIR}/references/review_protocols.md"; then
        xfail "BUG-004: review_protocols.md has 'Phase 6: Results' (should be Phase 3)"
    else
        if grep -q "### Phase 3: Results" "${REPO_DIR}/references/review_protocols.md"; then
            pass "BUG-004: review_protocols.md correctly uses 'Phase 3: Results'"
        else
            fail "BUG-004: Neither Phase 3 nor Phase 6 Results heading found"
        fi
    fi
}

# ──────────────────────────────────────────────────────────────────────
# BUG-005: Dangling BUG-005 reference
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-005-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_005_dangling_reference() {
    # BUG-005: quality_gate.sh references BUG-005 but it doesn't exist as a bug report
    # [Spec basis: quality_gate.sh line 116]
    # The comment "per BUG-005" implies a bug report that justifies the WARN downgrade.
    # The reference is dangling if no BUG-005 writeup or bug report explains the decision.
    local ref_count
    ref_count=$(grep -c "per BUG-005" "${GATE}" 2>/dev/null || echo 0)
    local comment_is_self_contained=false
    # Check if the comment itself includes the justification (not just the reference)
    local comment_line
    comment_line=$(grep "BUG-005" "${GATE}" 2>/dev/null)
    if echo "$comment_line" | grep -qi "because\|reason\|rationale\|justified"; then
        comment_is_self_contained=true
    fi

    if [ "$ref_count" -gt 0 ] && [ "$comment_is_self_contained" = false ]; then
        xfail "BUG-005: quality_gate.sh references 'per BUG-005' without self-contained justification"
    else
        pass "BUG-005: BUG-005 reference either removed or includes inline justification"
    fi
}

# ──────────────────────────────────────────────────────────────────────
# BUG-006: AGENTS.md not checked
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-006-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_006_agents_md_not_checked() {
    # BUG-006: AGENTS.md is Required: Yes but quality_gate.sh doesn't check it
    # [Spec basis: SKILL.md line 102]
    if grep -q "AGENTS" "${GATE}" 2>/dev/null; then
        pass "BUG-006: quality_gate.sh checks for AGENTS.md"
    else
        xfail "BUG-006: quality_gate.sh does not check for AGENTS.md (Required: Yes in SKILL.md)"
    fi
}

# ──────────────────────────────────────────────────────────────────────
# BUG-007: Version detection path asymmetry
# Skip guard: Remove this block to run the test (unskip after applying
# quality/patches/BUG-007-fix.patch)
# ──────────────────────────────────────────────────────────────────────

test_bug_007_version_path_asymmetry() {
    # BUG-007: Global version detection tries 6 paths, per-repo stamp check tries 4
    # [Spec basis: quality_gate.sh lines 59-67 vs 581-586]
    local global_paths per_repo_paths
    global_paths=$(sed -n '61p' "${GATE}" | grep -oE '"[^"]*SKILL\.md"' | wc -l | tr -d ' ')
    per_repo_paths=$(sed -n '581p' "${GATE}" | grep -oE '"[^"]*SKILL\.md"' | wc -l | tr -d ' ')

    if [ "$global_paths" -ne "$per_repo_paths" ]; then
        xfail "BUG-007: Version path asymmetry — global has ${global_paths} paths, per-repo has ${per_repo_paths}"
    else
        pass "BUG-007: Version detection path lists are consistent (${global_paths} paths each)"
    fi
}

# ──────────────────────────────────────────────────────────────────────
# Run all tests
# ──────────────────────────────────────────────────────────────────────

echo ""
echo "=== Regression Tests ==="

if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "001" ]; then
    test_bug_001_required_artifacts_warn_severity
    test_bug_001_all_warn_artifacts_missing
fi
if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "002" ]; then
    test_bug_002_functional_test_java_name
    test_bug_002_functional_test_ts_name
fi
if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "003" ]; then
    test_bug_003_eval_usage_in_gate
fi
if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "004" ]; then
    test_bug_004_phase_numbering
fi
if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "005" ]; then
    test_bug_005_dangling_reference
fi
if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "006" ]; then
    test_bug_006_agents_md_not_checked
fi
if [ -z "${RUN_BUG:-}" ] || [ "${RUN_BUG:-}" = "007" ]; then
    test_bug_007_version_path_asymmetry
fi

echo ""
echo "=================================="
echo "Results: ${PASS} pass, ${FAIL} fail, ${XFAIL} xfail out of ${TOTAL} tests"
echo "=================================="

if [ "$FAIL" -gt 0 ]; then
    exit 1
else
    exit 0
fi
