# Generated by Quality Playbook v1.5.3 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-28 · Project: quality-playbook

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from bin import benchmark_lib, citation_verifier, classify_project, role_map, run_playbook


REPO_ROOT = Path(__file__).resolve().parents[1]


def _extract_index_payload(index_text: str) -> dict:
    start = index_text.index("```json\n") + len("```json\n")
    end = index_text.index("\n```", start)
    return json.loads(index_text[start:end])


class CodeReviewRegressionTests(unittest.TestCase):
    @unittest.expectedFailure
    def test_bug_001_reference_docs_counts_as_docs_present(self) -> None:
        """BUG-001: reference_docs/ should suppress legacy code-only docs warnings."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            (repo / "reference_docs").mkdir()
            (repo / "reference_docs" / "design-notes.md").write_text("# notes\n", encoding="utf-8")
            self.assertTrue(run_playbook.docs_present(repo))

    def test_bug_002_phase2_gate_enforces_written_contract(self) -> None:
        """BUG-002: long placeholders without the required headings must
        not pass Phase 2.

        v1.5.4 Round 1 Council finding A1/B1/C1 incidentally fixed this:
        the new Phase 2 role-map gate fails when only EXPLORATION.md
        exists (no quality/exploration_role_map.json), so the long
        placeholder no longer slips through. The original BUG-002
        concern (length-only enforcement) is still imperfect but is
        now backstopped by the role-map presence check. Removed
        @expectedFailure since the gate now rejects this case."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            quality = repo / "quality"
            quality.mkdir()
            filler = "\n".join(f"line {i}" for i in range(1, 123))
            (quality / "EXPLORATION.md").write_text(filler, encoding="utf-8")
            gate = run_playbook.check_phase_gate(repo, "2")
            self.assertFalse(gate.ok)

    def test_bug_003_live_index_carries_role_breakdown(self) -> None:
        """BUG-003 (v1.5.4 migration): live INDEX writers must emit
        schema_version 2.0 with target_role_breakdown sourced from the
        Phase-1 role map at quality/exploration_role_map.json. The
        v1.5.3 form of this test asserted target_project_type =
        classification; that field was retired in v1.5.4 Part 1
        (Round 1 Council finding C2-1) and replaced by
        target_role_breakdown. The @expectedFailure marker that masked
        the migration regression has been removed; this test must
        pass on every v1.5.4 run."""
        for classification in ("Skill", "Hybrid"):
            with self.subTest(classification=classification):
                with tempfile.TemporaryDirectory() as tmp:
                    repo = Path(tmp)
                    (repo / "SKILL.md").write_text(
                        "# Skill\n\n" + ("word " * 500), encoding="utf-8"
                    )
                    (repo / "bin").mkdir()
                    (repo / "bin" / "tool.py").write_text(
                        "print('hello')\n", encoding="utf-8"
                    )
                    files = [{
                        "path": "SKILL.md", "role": "skill-prose",
                        "size_bytes": 1000, "rationale": "fixture",
                    }]
                    if classification == "Hybrid":
                        files.append({
                            "path": "bin/tool.py", "role": "code",
                            "size_bytes": 500, "rationale": "fixture",
                        })
                    role_map_doc = {
                        "schema_version": role_map.SCHEMA_VERSION,
                        "timestamp_start": "2026-04-28T00:00:00Z",
                        "files": files,
                        "breakdown": role_map.compute_breakdown(files),
                    }
                    quality = repo / "quality"
                    quality.mkdir(exist_ok=True)
                    (quality / "exploration_role_map.json").write_text(
                        json.dumps(role_map_doc), encoding="utf-8"
                    )
                    with mock.patch.object(
                        run_playbook.archive_lib,
                        "_git_head_sha",
                        return_value="deadbeef",
                    ):
                        run_playbook.write_live_index_stub(
                            repo, "20260428T131715Z"
                        )
                    stub_payload = _extract_index_payload(
                        (repo / "quality" / "INDEX.md").read_text(encoding="utf-8")
                    )
                    # Stub runs before Phase 1; target_role_breakdown
                    # is null and schema_version is 2.0.
                    self.assertEqual(stub_payload["schema_version"], "2.0")
                    self.assertIsNone(stub_payload["target_role_breakdown"])
                    self.assertNotIn("target_project_type", stub_payload)
                    run_playbook.write_live_index_final(
                        repo, "20260428T131715Z", gate_verdict="partial"
                    )
                    final_payload = _extract_index_payload(
                        (repo / "quality" / "INDEX.md").read_text(encoding="utf-8")
                    )
                    self.assertEqual(final_payload["schema_version"], "2.0")
                    breakdown = final_payload["target_role_breakdown"]
                    self.assertIsNotNone(breakdown)
                    self.assertIn("percentages", breakdown)
                    pcts = breakdown["percentages"]
                    if classification == "Skill":
                        self.assertGreater(pcts["skill_share"], 0)
                        self.assertEqual(pcts["code_share"], 0)
                    else:  # Hybrid
                        self.assertGreater(pcts["skill_share"], 0)
                        self.assertGreater(pcts["code_share"], 0)

    @unittest.expectedFailure
    def test_bug_004_cleanup_without_pid_files_stays_run_scoped(self) -> None:
        """BUG-004: missing PID files should not trigger workstation-wide pkill fallback."""
        with mock.patch.object(run_playbook, "discover_pid_files", return_value=[]), mock.patch.object(
            run_playbook, "_pkill_fallback"
        ) as fallback:
            run_playbook.kill_recorded_processes()
            fallback.assert_not_called()

    @unittest.expectedFailure
    def test_bug_005_installed_gate_retains_citation_verifier(self) -> None:
        """BUG-005: installed quality_gate.py should keep its Layer-1 verifier dependency."""
        with tempfile.TemporaryDirectory() as tmp:
            install_root = Path(tmp)
            gate_path = install_root / ".github" / "skills" / "quality_gate.py"
            gate_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(REPO_ROOT / ".github" / "skills" / "quality_gate" / "quality_gate.py", gate_path)
            probe = (
                "import importlib.util, pathlib, sys; "
                "path = pathlib.Path(sys.argv[1]); "
                "spec = importlib.util.spec_from_file_location('installed_quality_gate', path); "
                "mod = importlib.util.module_from_spec(spec); "
                "spec.loader.exec_module(mod); "
                "print('present' if mod._CITATION_VERIFIER is not None else 'missing')"
            )
            env = os.environ.copy()
            env["PYTHONPATH"] = str(install_root)
            result = subprocess.run(
                [sys.executable, "-c", probe, str(gate_path)],
                cwd=install_root,
                env=env,
                capture_output=True,
                text=True,
                check=True,
            )
            self.assertEqual(result.stdout.strip(), "present")

    @unittest.expectedFailure
    def test_bug_006_bootstrap_docs_match_live_release_framing(self) -> None:
        """BUG-006: curated bootstrap docs should match the live version and docs terminology."""
        skill_text = (REPO_ROOT / "SKILL.md").read_text(encoding="utf-8")
        live_version = next(
            line.split(":", 1)[1].strip()
            for line in skill_text.splitlines()
            if line.startswith("  version:")
        )
        for path in (
            REPO_ROOT / "docs_gathered" / "01_README_project.md",
            REPO_ROOT / "docs_gathered" / "29_improvement_axes_and_version_history.md",
        ):
            with self.subTest(path=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertIn(live_version, text)
                self.assertIn("reference_docs", text)

    @unittest.expectedFailure
    def test_bug_007_direct_root_and_harness_docs_surfaces_match(self) -> None:
        """BUG-007: direct-root bootstrap should expose the same effective docs set as the harness mirror."""
        expected = sorted(
            path.name
            for path in (REPO_ROOT / "docs_gathered").iterdir()
            if path.is_file() and path.suffix.lower() in {".md", ".txt"} and path.name != "README.md"
        )
        actual = sorted(
            path.relative_to(REPO_ROOT / "reference_docs").as_posix()
            for path in run_playbook._reference_docs_plaintext(REPO_ROOT / "reference_docs")
        )
        self.assertEqual(actual, expected)

    @unittest.expectedFailure
    def test_bug_008_later_phase_prompts_use_documented_fallback_list(self) -> None:
        """BUG-008: Phase 2-6 prompts should stay portable across all documented skill layouts."""
        for prompt in (
            run_playbook.phase2_prompt(),
            run_playbook.phase3_prompt(),
            run_playbook.phase4_prompt(),
            run_playbook.phase5_prompt(),
            run_playbook.phase6_prompt(),
        ):
            with self.subTest(prompt=prompt.splitlines()[0][:40]):
                self.assertIn("SKILL.md, .claude/skills/quality-playbook/SKILL.md", prompt)
                self.assertIn(".github/skills/SKILL.md, .github/skills/quality-playbook/SKILL.md", prompt)
                self.assertNotIn(".github/skills/references/", prompt)

    @unittest.expectedFailure
    def test_bug_009_skill_detection_uses_documented_four_path_order(self) -> None:
        """BUG-009: helper discovery should use the live four-path fallback order."""
        self.assertEqual(
            tuple(str(path) for path in benchmark_lib.SKILL_INSTALL_LOCATIONS),
            (
                "SKILL.md",
                ".claude/skills/quality-playbook/SKILL.md",
                ".github/skills/SKILL.md",
                ".github/skills/quality-playbook/SKILL.md",
            ),
        )

    @unittest.expectedFailure
    def test_bug_010_claude_orchestrator_uses_canonical_copilot_order(self) -> None:
        """BUG-010: the Claude orchestrator should list flat Copilot before nested Copilot."""
        claude_agent = (REPO_ROOT / "agents" / "quality-playbook-claude.agent.md").read_text(encoding="utf-8")
        self.assertLess(
            claude_agent.index("3. `.github/skills/SKILL.md`"),
            claude_agent.index("4. `.github/skills/quality-playbook/SKILL.md`"),
        )

    @unittest.expectedFailure
    def test_bug_011_citation_verifier_rejects_out_of_root_paths(self) -> None:
        """BUG-011: verify_citation should refuse source_paths that escape root before reading bytes."""
        with tempfile.TemporaryDirectory() as outside_dir, tempfile.TemporaryDirectory() as repo_dir:
            sentinel = Path(outside_dir) / "secret.txt"
            sentinel.write_text("alpha\nbeta\ngamma\n", encoding="utf-8")
            repo_root = Path(repo_dir)
            relative_traversal = os.path.relpath(sentinel, repo_root)
            for hostile in (str(sentinel), relative_traversal):
                with self.subTest(source_path=hostile):
                    citation = {"document": hostile, "line": 1}
                    formal_doc = {"source_path": hostile}
                    result = citation_verifier.verify_citation(citation, formal_doc, repo_root)
                    self.assertFalse(
                        result.ok,
                        f"verifier accepted out-of-root source_path {hostile!r} and produced excerpt {result.excerpt!r}",
                    )


if __name__ == "__main__":
    unittest.main()
