#!/bin/bash
# Generated by Quality Playbook v1.4.0 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-15 · Project: quality-playbook (bootstrap self-audit)
#
# Regression tests for confirmed bugs from the Phase 3 code review.
# Each test is marked with "# XFAIL:" to indicate it is expected to fail
# on unpatched code. When the bug is fixed, the test should pass and
# the XFAIL marker should be removed.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SKILL="${PROJECT_ROOT}/SKILL.md"
GATE="${PROJECT_ROOT}/quality_gate.sh"
AGENTS="${PROJECT_ROOT}/AGENTS.md"
TOOLKIT="${PROJECT_ROOT}/ai_context/TOOLKIT.md"
DEVCTX="${PROJECT_ROOT}/ai_context/DEVELOPMENT_CONTEXT.md"

PASS=0
FAIL=0
XFAIL=0
TOTAL=0

run_test() {
    local name="$1"
    local bug_id="$2"
    local expected_fail="$3"  # "xfail" or "pass"
    shift 3
    TOTAL=$((TOTAL + 1))
    
    local result
    if "$@" 2>/dev/null; then
        if [ "$expected_fail" = "xfail" ]; then
            echo "XPASS: ${name} (${bug_id}) — test passes but bug expected; fix may have been applied"
            PASS=$((PASS + 1))
        else
            echo "PASS: ${name}"
            PASS=$((PASS + 1))
        fi
    else
        if [ "$expected_fail" = "xfail" ]; then
            echo "XFAIL: ${name} (${bug_id}) — expected failure, bug confirmed"
            XFAIL=$((XFAIL + 1))
        else
            echo "FAIL: ${name}"
            FAIL=$((FAIL + 1))
        fi
    fi
}

# --- BUG-001: tdd_verified vs verified in Example 1 summary ---
# XFAIL: BUG-001 — SKILL.md line 127 uses "tdd_verified" but normative text (line 1394) requires "verified"
# Fix: Change "tdd_verified" to "verified" at SKILL.md line 127
test_bug_001_tdd_verified_key() {
    # The first canonical example must use "verified", not "tdd_verified"
    local example1_summary
    example1_summary=$(sed -n '110,130p' "$SKILL" | grep -c '"tdd_verified"')
    # Test passes if tdd_verified is NOT found in Example 1 (i.e., count is 0)
    [ "$example1_summary" -eq 0 ]
}

# --- BUG-002: Phase 7 not in plan overview ---
# XFAIL: BUG-002 — SKILL.md has Phase 7 at line 1890 but plan overview (lines 12-31) omits it
# Fix: Either add Phase 7 to plan overview or remove Phase 7 section
test_bug_002_phase7_in_plan_overview() {
    # Check if Phase 7 exists in the body
    local phase7_exists
    phase7_exists=$(grep -c '^## Phase 7:' "$SKILL")
    if [ "$phase7_exists" -eq 0 ]; then
        # Phase 7 removed — consistent
        return 0
    fi
    # Phase 7 exists — check it is in plan overview
    local plan_mentions_phase7
    plan_mentions_phase7=$(sed -n '12,31p' "$SKILL" | grep -ci 'phase 7')
    [ "$plan_mentions_phase7" -gt 0 ]
}

# --- BUG-003: Hardcoded .github/skills/references/ paths ---
# XFAIL: BUG-003 — SKILL.md hardcodes .github/skills/references/ in 16+ places
# Fix: Change all paths to relative references/ or add path resolution logic
test_bug_003_no_hardcoded_reference_paths() {
    local hardcoded_count
    hardcoded_count=$(grep -c '\.github/skills/references/' "$SKILL")
    # Test passes if zero hardcoded paths exist
    [ "$hardcoded_count" -eq 0 ]
}

# --- BUG-004: Gate does not validate TDD log status tags ---
# XFAIL: BUG-004 — SKILL.md line 1137 claims gate checks status tags, but gate only checks file existence
# Fix: Either add status tag validation to quality_gate.sh or correct SKILL.md claim
test_bug_004_gate_validates_status_tags_or_skill_doesnt_claim() {
    # Check if quality_gate.sh reads log file content (status tag)
    local gate_reads_tag
    gate_reads_tag=$(grep -cE '(head -1|sed -n 1p|awk.*NR==1).*(red\.log|green\.log)' "$GATE")
    if [ "$gate_reads_tag" -gt 0 ]; then
        return 0  # Gate validates tags — consistent
    fi
    # Gate doesn't validate tags — check SKILL.md doesn't claim it does
    local skill_claims_gate_checks
    skill_claims_gate_checks=$(grep -c 'quality_gate.sh. will check for its presence' "$SKILL")
    # Test passes if SKILL.md does NOT claim gate checks status tags
    [ "$skill_claims_gate_checks" -eq 0 ]
}

# --- BUG-005: 7 required artifacts not gate-checked ---
# XFAIL: BUG-005 — CONTRACTS.md, RUN_*.md, test_functional.*, AGENTS.md not in gate file checks
# Fix: Add file existence checks for all required artifacts to quality_gate.sh
test_bug_005_gate_checks_contracts_md() {
    # Check if quality_gate.sh validates CONTRACTS.md exists
    grep -q 'CONTRACTS.md' "$GATE"
}

# --- BUG-006: AGENTS.md missing Claude Code installation path ---
# XFAIL: BUG-006 — AGENTS.md only shows .github/skills/ installation, not .claude/skills/
# Fix: Add Claude Code installation instructions to AGENTS.md
test_bug_006_agents_md_has_claude_path() {
    grep -q '\.claude/skills' "$AGENTS"
}

# --- BUG-007: Artifact table verify.sh Created In says Phase 5 not Phase 2 ---
# XFAIL: BUG-007 — verify.sh listed as "Phase 5" but instructions say Phase 2
# Fix: Change "Phase 5" to "Phase 2" for verify.sh and receipt files in artifact table
test_bug_007_verify_sh_created_in_phase() {
    # Find the artifact table line for verify.sh and check if it says Phase 2
    local verify_line
    verify_line=$(grep -n 'mechanical/verify.sh' "$SKILL" | head -1)
    echo "$verify_line" | grep -qi 'Phase 2'
}

# --- BUG-008: Summary key validation missing total and verified ---
# XFAIL: BUG-008 — quality_gate.sh only checks confirmed_open, red_failed, green_failed
# Fix: Add total and verified to summary key checks in quality_gate.sh
test_bug_008_gate_checks_total_and_verified() {
    local checks_total checks_verified
    checks_total=$(grep -c '"total"' "$GATE" | grep -v 'total_patches\|total_groups')
    checks_verified=$(grep -c '"verified"' "$GATE")
    [ "$checks_total" -gt 0 ] && [ "$checks_verified" -gt 0 ]
}

# --- BUG-009: Unguarded glob in writeup for loop ---
# XFAIL: BUG-009 — quality_gate.sh line 507 has no nullglob guard
# Fix: Add nullglob guard or compgen check before the writeup loop
test_bug_009_writeup_loop_guarded() {
    # Check for nullglob or compgen guard near the writeup loop
    local has_guard
    has_guard=$(grep -cE '(nullglob|compgen.*BUG-)' "$GATE")
    [ "$has_guard" -gt 0 ]
}

# --- BUG-012: DEVELOPMENT_CONTEXT.md Phase 3 mislabel ---
# XFAIL: BUG-012 — verification.md labeled "Phase 3" but should be "Phase 6"
# Fix: Change "Phase 3" to "Phase 6" on the verification.md line
test_bug_012_devctx_verification_phase_label() {
    # The line mentioning verification.md should say Phase 6, not Phase 3
    local label
    label=$(grep 'verification.md' "$DEVCTX" | head -1)
    echo "$label" | grep -q 'Phase 6'
}

# --- BUG-013: TOOLKIT.md Quick Start missing Claude Code path ---
# XFAIL: BUG-013 — TOOLKIT.md only shows .github/skills/ installation
# Fix: Add .claude/skills/quality-playbook/ path to Quick Start section
test_bug_013_toolkit_has_claude_path() {
    grep -q '\.claude/skills' "$TOOLKIT"
}

# --- BUG-014: Dangling Phase 7 cross-references ---
# XFAIL: BUG-014 — Lines 436, 1797, 1821 reference Phase 7 which is not in plan overview
# Fix: Remove or update Phase 7 references to match plan overview
test_bug_014_no_dangling_phase7_refs() {
    # Count references to "Phase 7" outside the Phase 7 section definition itself
    local phase7_refs
    phase7_refs=$(grep -n 'Phase 7' "$SKILL" | grep -cv '^1890:')
    # If Phase 7 is in the plan overview, refs are fine. If not, they are dangling.
    local in_overview
    in_overview=$(sed -n '12,31p' "$SKILL" | grep -ci 'phase 7')
    if [ "$in_overview" -gt 0 ]; then
        return 0  # Phase 7 is in overview, references are valid
    fi
    # Phase 7 not in overview — no references should exist outside its own section
    [ "$phase7_refs" -eq 0 ]
}

# --- BUG-015: Per-bug fields not classified required/optional ---
# XFAIL: BUG-015 — Example 2 has 7 extra fields not classified in normative text
# Fix: Add explicit required/optional classification for additional fields
test_bug_015_extra_fields_classified() {
    # Check if SKILL.md explicitly classifies regression_patch etc. as required or optional
    local classification
    classification=$(grep -ciE '(optional|required).*regression_patch|regression_patch.*(optional|required)' "$SKILL")
    [ "$classification" -gt 0 ]
}


# --- BUG-016: SKILL.md says "five strategies" but only four exist ---
# XFAIL: BUG-016 — SKILL.md line 210 says "five strategies"; iteration.md defines four; line 1879 says "four"
# Fix: Change "five" to "four" on SKILL.md line 210
# Source: Spec Audit SA-06
test_bug_016_strategy_count_consistent() {
    local line210
    line210=$(sed -n '210p' "$SKILL")
    if echo "$line210" | grep -q 'five strategies'; then
        return 1
    fi
    return 0
}

# --- BUG-017: verification.md references Phase 7 ---
# XFAIL: BUG-017 — references/verification.md line 75 references Phase 7 which is not in plan overview
# Fix: Replace Phase 7 reference with appropriate destination or remove
# Source: Spec Audit SA-14
test_bug_017_verification_md_no_phase7() {
    local verif="${PROJECT_ROOT}/references/verification.md"
    local phase7_refs
    phase7_refs=$(grep -ci 'phase 7' "$verif" || true)
    phase7_refs=${phase7_refs:-0}
    [ "$phase7_refs" -eq 0 ]
}

# --- BUG-018: verification.md hardcodes .github/skills/SKILL.md ---
# XFAIL: BUG-018 — references/verification.md line 172 hardcodes .github/skills/SKILL.md path
# Fix: Remove parenthetical or use installation-agnostic language
# Source: Spec Audit SA-15
test_bug_018_verification_md_no_hardcoded_skill_path() {
    local verif="${PROJECT_ROOT}/references/verification.md"
    local hc_count
    hc_count=$(grep -c '\.github/skills/SKILL\.md' "$verif" || true)
    hc_count=${hc_count:-0}
    [ "$hc_count" -eq 0 ]
}

# ==============================================================
# Run all tests
# ==============================================================

echo "=== Regression Tests for Code Review and Spec Audit Bugs ==="
echo ""

run_test "BUG-001: tdd_verified vs verified in Example 1" "BUG-001" "xfail" test_bug_001_tdd_verified_key
run_test "BUG-002: Phase 7 not in plan overview" "BUG-002" "xfail" test_bug_002_phase7_in_plan_overview
run_test "BUG-003: Hardcoded reference paths" "BUG-003" "xfail" test_bug_003_no_hardcoded_reference_paths
run_test "BUG-004: Gate status tag claim vs implementation" "BUG-004" "xfail" test_bug_004_gate_validates_status_tags_or_skill_doesnt_claim
run_test "BUG-005: CONTRACTS.md not gate-checked" "BUG-005" "xfail" test_bug_005_gate_checks_contracts_md
run_test "BUG-006: AGENTS.md missing Claude Code path" "BUG-006" "xfail" test_bug_006_agents_md_has_claude_path
run_test "BUG-007: verify.sh Created In Phase mismatch" "BUG-007" "xfail" test_bug_007_verify_sh_created_in_phase
run_test "BUG-008: Gate missing total/verified summary keys" "BUG-008" "xfail" test_bug_008_gate_checks_total_and_verified
run_test "BUG-009: Unguarded glob in writeup loop" "BUG-009" "xfail" test_bug_009_writeup_loop_guarded
run_test "BUG-012: DEVELOPMENT_CONTEXT.md Phase 3 mislabel" "BUG-012" "xfail" test_bug_012_devctx_verification_phase_label
run_test "BUG-013: TOOLKIT.md missing Claude Code path" "BUG-013" "xfail" test_bug_013_toolkit_has_claude_path
run_test "BUG-014: Dangling Phase 7 cross-references" "BUG-014" "xfail" test_bug_014_no_dangling_phase7_refs
run_test "BUG-015: Extra per-bug fields not classified" "BUG-015" "xfail" test_bug_015_extra_fields_classified
run_test "BUG-016: Strategy count inconsistency" "BUG-016" "xfail" test_bug_016_strategy_count_consistent
run_test "BUG-017: verification.md Phase 7 reference" "BUG-017" "xfail" test_bug_017_verification_md_no_phase7
run_test "BUG-018: verification.md hardcoded SKILL.md path" "BUG-018" "xfail" test_bug_018_verification_md_no_hardcoded_skill_path

echo ""
echo "=== Results ==="
echo "Total: ${TOTAL}, Pass: ${PASS}, XFail: ${XFAIL}, Fail: ${FAIL}"

if [ "$FAIL" -gt 0 ]; then
    echo "RESULT: ${FAIL} unexpected failure(s)"
    exit 1
else
    echo "RESULT: All tests expected-fail or pass"
    exit 0
fi
