#!/bin/bash
# Generated by Quality Playbook v1.4.0 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-15 · Project: quality-playbook (QFB-bootstrap)
#
# Functional tests for quality_gate.sh and SKILL.md specification consistency.
# This is a bash test harness because quality_gate.sh is the only executable code.
#
# Usage: bash quality/test_functional.sh
#   Runs all tests and reports PASS/FAIL counts.
#   Exit 0 if all pass, exit 1 if any fail.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
GATE="${REPO_DIR}/quality_gate.sh"
PASS=0
FAIL=0
TOTAL=0

pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); TOTAL=$((TOTAL + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); TOTAL=$((TOTAL + 1)); }

setup_test_dir() {
    local dir
    dir=$(mktemp -d)
    mkdir -p "${dir}/quality"
    echo "$dir"
}

create_minimal_artifacts() {
    local dir="$1"
    local q="${dir}/quality"
    # Create the 6 FAIL-checked artifacts
    echo "# BUGS" > "${q}/BUGS.md"
    echo "# REQUIREMENTS" > "${q}/REQUIREMENTS.md"
    echo "# QUALITY" > "${q}/QUALITY.md"
    echo "# PROGRESS" > "${q}/PROGRESS.md"
    echo "# COVERAGE" > "${q}/COVERAGE_MATRIX.md"
    echo "# COMPLETENESS" > "${q}/COMPLETENESS_REPORT.md"
}

create_full_artifacts() {
    local dir="$1"
    local q="${dir}/quality"
    create_minimal_artifacts "$dir"
    # Create the WARN-checked artifacts
    echo "# CONTRACTS" > "${q}/CONTRACTS.md"
    echo "# RUN_CODE_REVIEW" > "${q}/RUN_CODE_REVIEW.md"
    echo "# RUN_SPEC_AUDIT" > "${q}/RUN_SPEC_AUDIT.md"
    echo "# RUN_INTEGRATION_TESTS" > "${q}/RUN_INTEGRATION_TESTS.md"
    echo "# RUN_TDD_TESTS" > "${q}/RUN_TDD_TESTS.md"
    echo "#!/bin/bash" > "${q}/test_functional.sh"
}

cleanup() {
    [ -n "${1:-}" ] && rm -rf "$1"
}

# ──────────────────────────────────────────────────────────────────────
# Group 1: Spec Requirements
# ──────────────────────────────────────────────────────────────────────

echo ""
echo "=== Spec Requirements ==="

# [REQ-001] Artifact contract table: SKILL.md lists required artifacts
test_req001_skill_md_artifact_table_exists() {
    # [Req: formal — SKILL.md lines 83-115]
    # Verify SKILL.md contains the artifact contract table with Required column
    if grep -q "| Artifact | Location | Required? | Created In |" "${REPO_DIR}/SKILL.md"; then
        pass "REQ-001: SKILL.md contains artifact contract table header"
    else
        fail "REQ-001: SKILL.md artifact contract table header not found"
    fi
}
test_req001_skill_md_artifact_table_exists

# [REQ-001] All Required: Yes artifacts are listed in SKILL.md
test_req001_required_artifacts_listed() {
    local count
    count=$(grep -c "| Yes |" "${REPO_DIR}/SKILL.md" || true)
    if [ "$count" -ge 10 ]; then
        pass "REQ-001: SKILL.md lists ${count} required artifacts (expected >=10)"
    else
        fail "REQ-001: SKILL.md lists only ${count} required artifacts (expected >=10)"
    fi
}
test_req001_required_artifacts_listed

# [REQ-002] quality_gate.sh checks primary artifacts with fail()
test_req002_primary_artifacts_use_fail() {
    # [Req: formal — SKILL.md lines 83-85, quality_gate.sh lines 106-113]
    local all_fail=true
    for artifact in BUGS.md REQUIREMENTS.md QUALITY.md PROGRESS.md COVERAGE_MATRIX.md COMPLETENESS_REPORT.md; do
        if ! grep -A2 "\"${artifact}\"" "${GATE}" 2>/dev/null | grep -q "fail"; then
            # Check via the loop pattern
            if grep -q "for f in.*${artifact}" "${GATE}" 2>/dev/null; then
                local loop_line
                loop_line=$(grep -n "for f in.*${artifact}" "${GATE}" | head -1 | cut -d: -f1)
                if ! sed -n "${loop_line},$((loop_line + 10))p" "${GATE}" | grep -q "fail"; then
                    all_fail=false
                fi
            fi
        fi
    done
    if [ "$all_fail" = true ]; then
        pass "REQ-002: Primary artifacts use fail() in quality_gate.sh"
    else
        fail "REQ-002: Some primary artifacts do not use fail()"
    fi
}
test_req002_primary_artifacts_use_fail

# [REQ-002] KNOWN BUG: Secondary artifacts use warn() instead of fail()
test_req002_secondary_artifacts_severity() {
    # [Req: formal — SKILL.md lines 83-85]
    # This test documents the known inconsistency: these should use fail() per SKILL.md
    # but currently use warn() in quality_gate.sh
    # The gate uses a for-loop at line 117-123 that iterates over these artifacts and uses warn()
    if grep -q "for f in CONTRACTS.md RUN_CODE_REVIEW.md" "${GATE}" 2>/dev/null; then
        # Check if the loop body uses warn
        local loop_start
        loop_start=$(grep -n "for f in CONTRACTS.md" "${GATE}" | head -1 | cut -d: -f1)
        if [ -n "$loop_start" ] && sed -n "${loop_start},$((loop_start + 8))p" "${GATE}" | grep -q "warn"; then
            pass "REQ-002: Confirmed secondary artifacts use warn() in for-loop (known inconsistency with SKILL.md)"
        else
            fail "REQ-002: Secondary artifacts loop found but warn() not detected"
        fi
    else
        fail "REQ-002: Secondary artifacts loop not found in quality_gate.sh"
    fi
}
test_req002_secondary_artifacts_severity

# [REQ-002] AGENTS.md not checked by quality_gate.sh
test_req002_agents_md_not_checked() {
    # [Req: formal — SKILL.md line 102]
    if grep -q "AGENTS.md" "${GATE}"; then
        pass "REQ-002: quality_gate.sh references AGENTS.md"
    else
        pass "REQ-002: Confirmed AGENTS.md is NOT checked by quality_gate.sh (known gap per CB-5)"
    fi
}
test_req002_agents_md_not_checked

# [REQ-003] Phase 2 entry gate checks 6 section titles
test_req003_phase2_entry_gate() {
    # [Req: formal — SKILL.md lines 893-902]
    local sections=("Open Exploration Findings" "Quality Risks" "Pattern Applicability Matrix" "Pattern Deep Dive" "Candidate Bugs for Phase 2" "Gate Self-Check")
    local found=0
    for section in "${sections[@]}"; do
        if grep -q "$section" "${REPO_DIR}/SKILL.md"; then
            found=$((found + 1))
        fi
    done
    if [ "$found" -eq 6 ]; then
        pass "REQ-003: SKILL.md Phase 2 entry gate references all 6 required section titles"
    else
        fail "REQ-003: SKILL.md Phase 2 entry gate only references ${found}/6 section titles"
    fi
}
test_req003_phase2_entry_gate

# [REQ-004] Reference file resolution fallback chain
test_req004_fallback_chain_defined() {
    # [Req: formal — SKILL.md lines 44-53]
    local paths_found=0
    for path_pattern in "references/" ".claude/skills/quality-playbook/references/" ".github/skills/quality-playbook/references/"; do
        if grep -qF "$path_pattern" "${REPO_DIR}/SKILL.md"; then
            paths_found=$((paths_found + 1))
        fi
    done
    if [ "$paths_found" -ge 3 ]; then
        pass "REQ-004: SKILL.md defines ${paths_found} fallback paths for reference files"
    else
        fail "REQ-004: SKILL.md only defines ${paths_found} fallback paths (expected >=3)"
    fi
}
test_req004_fallback_chain_defined

# [REQ-006] quality_gate.sh exit code logic
test_req006_exit_code_logic() {
    # [Req: formal — quality_gate.sh lines 664-676]
    if grep -q '"$FAIL" -gt 0\|FAIL -gt 0' "${GATE}"; then
        pass "REQ-006: quality_gate.sh checks FAIL > 0 for exit code determination"
    else
        fail "REQ-006: quality_gate.sh exit code logic not found"
    fi
}
test_req006_exit_code_logic

# [REQ-007] Test file detection pattern
test_req007_test_file_detection() {
    # [Req: formal — SKILL.md line 69, quality_gate.sh line 125]
    if grep -q "test_functional\.\*" "${GATE}"; then
        pass "REQ-007: quality_gate.sh checks test_functional.* pattern"
    else
        fail "REQ-007: quality_gate.sh does not check test_functional.* pattern"
    fi
    # Check for SKILL.md-allowed alternative names
    local alternatives_found=0
    for pattern in "FunctionalSpec" "FunctionalTest" "functional.test"; do
        if grep -q "$pattern" "${GATE}" 2>/dev/null; then
            alternatives_found=$((alternatives_found + 1))
        fi
    done
    if [ "$alternatives_found" -eq 0 ]; then
        pass "REQ-007: Confirmed quality_gate.sh does NOT check SKILL.md-allowed alternative names (known gap per CB-3)"
    else
        pass "REQ-007: quality_gate.sh checks ${alternatives_found} alternative test file names"
    fi
}
test_req007_test_file_detection

# [REQ-008] Version stamp format
test_req008_version_stamp_format() {
    # [Req: formal — SKILL.md lines 908-922]
    if grep -q "Generated by.*Quality Playbook.*v" "${REPO_DIR}/SKILL.md"; then
        pass "REQ-008: SKILL.md defines the version stamp format"
    else
        # The stamp template is in a code block, check for the pattern
        if grep -q 'Generated by \[Quality Playbook\]' "${REPO_DIR}/SKILL.md"; then
            pass "REQ-008: SKILL.md defines the version stamp format (Markdown link format)"
        else
            fail "REQ-008: Version stamp format not found in SKILL.md"
        fi
    fi
}
test_req008_version_stamp_format

# [REQ-009] eval usage with user-supplied paths
test_req009_eval_usage() {
    # [Req: inferred — quality_gate.sh lines 439-448]
    local eval_count
    eval_count=$(grep -c 'eval ' "${GATE}" 2>/dev/null || echo 0)
    if [ "$eval_count" -gt 0 ]; then
        pass "REQ-009: Confirmed quality_gate.sh uses eval ${eval_count} time(s) (known risk per CB-4)"
    else
        pass "REQ-009: quality_gate.sh does not use eval"
    fi
}
test_req009_eval_usage

# [REQ-010] review_protocols.md Phase numbering
test_req010_phase_numbering() {
    # [Req: formal — references/review_protocols.md line 378]
    if grep -q "### Phase 6: Results" "${REPO_DIR}/references/review_protocols.md"; then
        pass "REQ-010: Confirmed review_protocols.md has 'Phase 6: Results' (known numbering error per CB-2)"
    else
        pass "REQ-010: review_protocols.md Phase 6 numbering error has been fixed"
    fi
}
test_req010_phase_numbering

# [REQ-011] Dangling BUG-005 reference
test_req011_dangling_bug_reference() {
    # [Req: inferred — quality_gate.sh line 116]
    if grep -q "BUG-005" "${GATE}"; then
        # Check if BUG-005 is documented anywhere
        local found_doc=false
        for f in "${REPO_DIR}"/*.md "${REPO_DIR}"/quality/*.md "${REPO_DIR}"/references/*.md; do
            if [ -f "$f" ] && grep -q "BUG-005" "$f" 2>/dev/null; then
                found_doc=true
                break
            fi
        done
        if [ "$found_doc" = true ]; then
            pass "REQ-011: BUG-005 reference in quality_gate.sh resolves to documentation"
        else
            pass "REQ-011: Confirmed BUG-005 reference is dangling (known issue per CB-1)"
        fi
    else
        pass "REQ-011: No BUG-005 reference in quality_gate.sh"
    fi
}
test_req011_dangling_bug_reference

# ──────────────────────────────────────────────────────────────────────
# Group 2: Fitness Scenarios from QUALITY.md
# ──────────────────────────────────────────────────────────────────────

echo ""
echo "=== Fitness Scenarios ==="

# Scenario 1: The Silent Gate Pass
test_scenario1_silent_gate_pass() {
    # [Req: formal — QUALITY.md Scenario 1]
    # Create a directory with only the FAIL-checked artifacts, missing all WARN-checked ones
    local dir
    dir=$(setup_test_dir)
    create_minimal_artifacts "$dir"
    # Copy SKILL.md so version detection works
    cp "${REPO_DIR}/SKILL.md" "$dir/"

    local exit_code=0
    bash "${GATE}" "$dir" > /dev/null 2>&1 || exit_code=$?

    if [ "$exit_code" -eq 0 ]; then
        pass "Scenario 1: Confirmed silent gate pass -- gate exits 0 with missing required artifacts (known bug)"
    else
        pass "Scenario 1: Gate correctly fails when WARN-checked artifacts are missing"
    fi
    cleanup "$dir"
}
test_scenario1_silent_gate_pass

# Scenario 2: The Confused Agent (Phase numbering)
test_scenario2_phase_numbering_collision() {
    # [Req: formal — QUALITY.md Scenario 2]
    # Verify the numbering collision exists
    local phase_numbers
    phase_numbers=$(grep -E "^### Phase [0-9]+:" "${REPO_DIR}/references/review_protocols.md" | grep -oE "Phase [0-9]+" | sort)
    if echo "$phase_numbers" | grep -q "Phase 6"; then
        pass "Scenario 2: Confirmed Phase 6 numbering collision in review_protocols.md"
    else
        pass "Scenario 2: Phase numbering is sequential (collision fixed)"
    fi
}
test_scenario2_phase_numbering_collision

# Scenario 3: The Invisible Test File
test_scenario3_invisible_test_file() {
    # [Req: formal — QUALITY.md Scenario 3]
    local dir
    dir=$(setup_test_dir)
    create_full_artifacts "$dir"
    # Replace test_functional.sh with FunctionalTest.java
    rm "${dir}/quality/test_functional.sh"
    echo "public class FunctionalTest {}" > "${dir}/quality/FunctionalTest.java"
    cp "${REPO_DIR}/SKILL.md" "$dir/"

    local output
    output=$(bash "${GATE}" "$dir" 2>&1 || true)

    if echo "$output" | grep -qi "test_functional.*missing\|WARN.*test_functional"; then
        pass "Scenario 3: Confirmed gate misses FunctionalTest.java (known detection gap)"
    else
        pass "Scenario 3: Gate detects FunctionalTest.java"
    fi
    cleanup "$dir"
}
test_scenario3_invisible_test_file

# Scenario 4: The Injection Vector
test_scenario4_eval_injection_risk() {
    # [Req: inferred — QUALITY.md Scenario 4]
    # Verify eval is used with a variable that comes from user input
    if grep -n 'eval.*find.*repo_dir\|eval.*\${repo_dir}' "${GATE}" > /dev/null 2>&1; then
        pass "Scenario 4: Confirmed eval used with repo_dir variable (known injection risk)"
    else
        pass "Scenario 4: eval with user-supplied paths not found (fixed)"
    fi
}
test_scenario4_eval_injection_risk

# Scenario 5: The Missing AGENTS.md Check
test_scenario5_agents_md_not_checked() {
    # [Req: formal — QUALITY.md Scenario 5]
    if grep -q "AGENTS" "${GATE}"; then
        pass "Scenario 5: quality_gate.sh checks for AGENTS.md"
    else
        pass "Scenario 5: Confirmed AGENTS.md not checked by quality_gate.sh (known gap)"
    fi
}
test_scenario5_agents_md_not_checked

# Scenario 6: The Dangling Reference
test_scenario6_dangling_reference() {
    # [Req: inferred — QUALITY.md Scenario 6]
    local bug005_in_gate bug005_documented
    bug005_in_gate=$(grep -c "BUG-005" "${GATE}" 2>/dev/null || echo 0)
    bug005_documented=0
    for f in "${REPO_DIR}"/quality/BUGS.md "${REPO_DIR}"/quality/writeups/BUG-005.md; do
        [ -f "$f" ] && bug005_documented=1
    done
    if [ "$bug005_in_gate" -gt 0 ] && [ "$bug005_documented" -eq 0 ]; then
        pass "Scenario 6: Confirmed BUG-005 reference is dangling (referenced but not documented)"
    elif [ "$bug005_in_gate" -eq 0 ]; then
        pass "Scenario 6: BUG-005 reference removed from quality_gate.sh"
    else
        pass "Scenario 6: BUG-005 reference resolves to documentation"
    fi
}
test_scenario6_dangling_reference

# Scenario 7: The Stale Artifact Passthrough
test_scenario7_stale_date_acceptance() {
    # [Req: inferred — QUALITY.md Scenario 7]
    # Verify quality_gate.sh's date validation rejects future dates but accepts ancient dates
    if grep -q "future" "${GATE}" && ! grep -q "date.*too.*old\|date.*stale\|date.*lower" "${GATE}"; then
        pass "Scenario 7: Confirmed gate rejects future dates but has no lower bound (stale dates pass)"
    else
        pass "Scenario 7: Gate has date freshness validation"
    fi
}
test_scenario7_stale_date_acceptance

# ──────────────────────────────────────────────────────────────────────
# Group 3: Boundary and Edge Cases
# ──────────────────────────────────────────────────────────────────────

echo ""
echo "=== Boundary and Edge Cases ==="

# Edge case: quality_gate.sh with no arguments
test_edge_no_arguments() {
    # [Req: inferred — quality_gate.sh argument parsing]
    local exit_code=0
    bash "${GATE}" > /dev/null 2>&1 || exit_code=$?
    # Should handle gracefully (either show usage or process current dir)
    if [ "$exit_code" -le 1 ]; then
        pass "Edge: quality_gate.sh handles no arguments (exit ${exit_code})"
    else
        fail "Edge: quality_gate.sh crashed with no arguments (exit ${exit_code})"
    fi
}
test_edge_no_arguments

# Edge case: quality_gate.sh with nonexistent directory
test_edge_nonexistent_dir() {
    local exit_code=0
    bash "${GATE}" "/nonexistent/path/that/does/not/exist" > /dev/null 2>&1 || exit_code=$?
    if [ "$exit_code" -ge 1 ]; then
        pass "Edge: quality_gate.sh fails on nonexistent directory (exit ${exit_code})"
    else
        fail "Edge: quality_gate.sh did not fail on nonexistent directory"
    fi
}
test_edge_nonexistent_dir

# Edge case: quality_gate.sh with empty quality directory
test_edge_empty_quality_dir() {
    local dir
    dir=$(setup_test_dir)
    cp "${REPO_DIR}/SKILL.md" "$dir/"
    local exit_code=0
    bash "${GATE}" "$dir" > /dev/null 2>&1 || exit_code=$?
    if [ "$exit_code" -eq 1 ]; then
        pass "Edge: quality_gate.sh fails on empty quality directory (exit 1)"
    else
        fail "Edge: quality_gate.sh did not fail on empty quality directory (exit ${exit_code})"
    fi
    cleanup "$dir"
}
test_edge_empty_quality_dir

# Edge case: SKILL.md version detection from different locations
test_edge_version_detection() {
    # [Req: formal — quality_gate.sh lines 59-67]
    # Verify version detection finds SKILL.md in the repo root
    local version
    version=$(grep -m1 'version:' "${REPO_DIR}/SKILL.md" 2>/dev/null | sed 's/.*version: *//' | tr -d ' ')
    if [ -n "$version" ]; then
        pass "Edge: Version detected from SKILL.md: ${version}"
    else
        fail "Edge: Could not extract version from SKILL.md"
    fi
}
test_edge_version_detection

# Edge case: json_has_key with key inside string value
test_edge_json_has_key_false_match() {
    # [Req: inferred — quality_gate.sh lines 75-78]
    local tmpfile
    tmpfile=$(mktemp)
    # Create JSON where "verdict" appears only inside a string value, not as a key
    cat > "$tmpfile" << 'JSONEOF'
{
    "id": "BUG-001",
    "description": "The verdict field was missing"
}
JSONEOF
    # json_has_key uses grep for "verdict" -- check if it would match inside the description
    # The word "verdict" appears inside the description value, not as a JSON key
    local match_count
    match_count=$(grep -c '"verdict"' "$tmpfile" 2>/dev/null | tr -d '[:space:]')
    [ -z "$match_count" ] && match_count=0
    if [ "$match_count" -gt 0 ]; then
        pass "Edge: Confirmed json_has_key grep pattern matches 'verdict' inside string values (known limitation)"
    else
        # The test JSON uses the word verdict inside a string value
        # Check if the pattern is present at all
        if grep -q 'verdict' "$tmpfile"; then
            pass "Edge: 'verdict' word present in JSON but not as quoted key (grep would miss it)"
        else
            fail "Edge: Test JSON does not contain the word 'verdict'"
        fi
    fi
    rm -f "$tmpfile"
}
test_edge_json_has_key_false_match

# Edge case: --general vs --benchmark strictness
test_edge_strictness_modes() {
    # [Req: formal — quality_gate.sh lines 40, 50-54]
    if grep -q 'STRICTNESS="benchmark"' "${GATE}" && grep -q '"general"' "${GATE}"; then
        pass "Edge: quality_gate.sh supports both --benchmark and --general modes"
    else
        fail "Edge: quality_gate.sh missing strictness mode support"
    fi
}
test_edge_strictness_modes

# Edge case: quality_gate.sh set -uo pipefail
test_edge_strict_bash_mode() {
    # [Req: inferred — quality_gate.sh line 32]
    if grep -q "set -uo pipefail\|set -euo pipefail" "${GATE}"; then
        pass "Edge: quality_gate.sh uses strict bash mode (set -uo pipefail)"
    else
        fail "Edge: quality_gate.sh does not use strict bash mode"
    fi
}
test_edge_strict_bash_mode

# Edge case: Bug heading format regex
test_edge_bug_heading_regex() {
    # [Req: formal — quality_gate.sh lines 168-205]
    if grep -q 'BUG-\[0-9\]' "${GATE}"; then
        pass "Edge: quality_gate.sh uses BUG-[0-9] heading pattern for bug counting"
    else
        fail "Edge: quality_gate.sh bug heading pattern not found"
    fi
}
test_edge_bug_heading_regex

# Edge case: Sidecar JSON schema_version check
test_edge_sidecar_schema_version() {
    # [Req: formal — SKILL.md lines 120-145]
    if grep -q "schema_version" "${GATE}"; then
        pass "Edge: quality_gate.sh validates schema_version in sidecar JSON"
    else
        fail "Edge: quality_gate.sh does not check schema_version"
    fi
}
test_edge_sidecar_schema_version

# ──────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────

echo ""
echo "=================================="
echo "Results: ${PASS} passed, ${FAIL} failed out of ${TOTAL} tests"
echo "=================================="

if [ "$FAIL" -gt 0 ]; then
    exit 1
else
    exit 0
fi
