#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.3 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-28 · Project: quality-playbook

set -euo pipefail

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
run_playbook = (repo / "bin" / "run_playbook.py").read_text(encoding="utf-8")
assert '"claude -p"' in run_playbook, 'line 2841 should still include the "claude -p" pkill pattern'
assert '"gh copilot -p"' in run_playbook, 'line 2843 should still include the "gh copilot -p" pkill pattern'
assert "if not pid_files:" in run_playbook, "cleanup fallback branch should still trigger when no PID files exist"
print("probe-1 ok: cleanup fallback still widens to generic pkill patterns")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
setup = (repo / "repos" / "setup_repos.sh").read_text(encoding="utf-8")
gate = (repo / ".github" / "skills" / "quality_gate" / "quality_gate.py").read_text(encoding="utf-8")
assert "quality_gate.py" in setup, "setup script should still copy the standalone gate entry point"
assert "citation_verifier.py" not in setup, "setup script unexpectedly started copying citation_verifier.py"
assert "_CITATION_VERIFIER = None" in gate, "gate should still tolerate missing citation_verifier import"
assert "byte-equality skipped" in gate, "gate should still warn-and-skip when citation_verifier is absent"
print("probe-2 ok: installed citation-verifier gap still exists")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
reference_docs = repo / "reference_docs"
docs_gathered = repo / "docs_gathered"
setup = (repo / "repos" / "setup_repos.sh").read_text(encoding="utf-8")
root_files = sorted(
    str(p.relative_to(reference_docs))
    for p in reference_docs.rglob("*")
    if p.is_file()
)
doc_files = sorted(
    str(p.relative_to(docs_gathered))
    for p in docs_gathered.glob("*.md")
)
assert root_files == [".gitkeep"], f"expected only the root .gitkeep file in reference_docs/, got {root_files}"
assert (reference_docs / "cite").is_dir(), "expected reference_docs/cite/ directory to exist even when empty"
assert len(doc_files) >= 10, f"expected populated docs_gathered/, got only {len(doc_files)} markdown files"
assert 'cp -R "${dst}/docs_gathered/." "${dst}/reference_docs/"' in setup, "harness should still mirror docs_gathered into reference_docs/"
print("probe-3 ok: direct-root and harness installs still expose different docs surfaces")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
curated = (repo / "docs_gathered" / "03_DEVELOPMENT_CONTEXT.md").read_text(encoding="utf-8")
live = (repo / "ai_context" / "DEVELOPMENT_CONTEXT.md").read_text(encoding="utf-8")
assert "Stdlib-only tests for the runner package (36 tests)" in curated, "curated development context no longer contains the stale 36-test claim"
assert "Mechanical validation (14 checks, 1100+ lines, Python 3.8+)" in curated, "curated development context no longer contains the stale 14-check claim"
assert "test_quality_gate.py  ← 108 stdlib-only unit tests" in curated, "curated development context no longer contains the stale 108-test claim"
assert "Benchmark runner + skill-derivation modules (662 tests at v1.5.3)" in live, "live development context should advertise 662 runner tests"
assert "Quality gate package (221 tests at v1.5.3" in live, "live development context should advertise 221 gate tests"
print("probe-4 ok: curated development-context counts are stale relative to the live repo")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
dg_readme = (repo / "docs_gathered" / "README.md").read_text(encoding="utf-8")
dg_index = (repo / "docs_gathered" / "INDEX.md").read_text(encoding="utf-8")
skill = (repo / "SKILL.md").read_text(encoding="utf-8")
assert "v1.5.1 self-audit bootstrap run" in dg_readme, "docs_gathered/README.md no longer shows the stale v1.5.1 framing"
assert "v1.5.1" in dg_index, "docs_gathered/INDEX.md no longer shows the stale v1.5.1 framing"
assert "version: 1.5.3" in skill, "live SKILL.md should advertise the current v1.5.3 release"
print("probe-5 ok: curated bootstrap docs still advertise the older v1.5.1 framing")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
gate = (repo / ".github" / "skills" / "quality_gate" / "quality_gate.py").read_text(encoding="utf-8")
start = gate.index("def check_v1_5_0_index_md")
end = gate.index("def check_v1_5_0_semantic_check")
index_check = gate[start:end]
start = gate.index("def check_project_type_consistency")
end = gate.index("def check_v1_5_2_cardinality_gate")
type_check = gate[start:end]
assert '"target_project_type",' in gate, "gate should still list target_project_type in the shared INDEX required-fields set"
assert "project_type.json" not in index_check, "INDEX gate unexpectedly started consulting project_type.json"
assert "classification" in type_check, "project-type consistency check should still inspect classification"
assert "INDEX.md" not in type_check, "project-type consistency check unexpectedly started consulting INDEX.md"
print("probe-6 ok: gate still lacks an INDEX-vs-project_type cross-check")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
run_playbook = (repo / "bin" / "run_playbook.py").read_text(encoding="utf-8")
assert ".github/skills/SKILL.md - read the Phase 2 section" in run_playbook, "phase2 prompt text no longer shows the hardcoded flat path"
assert ".github/skills/references/review_protocols.md" in run_playbook, "later-phase prompt family no longer shows the flat references path"
print("probe-7 ok: later-phase prompt family still hardcodes flat Copilot skill/reference paths")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
bench = (repo / "bin" / "benchmark_lib.py").read_text(encoding="utf-8")
runner = (repo / "bin" / "run_playbook.py").read_text(encoding="utf-8")
assert 'Path(".github") / "skills" / "SKILL.md"' in bench.split("SKILL_INSTALL_LOCATIONS =", 1)[1], "helper tuple no longer contains the flat Copilot path literal"
assert 'Path("SKILL.md")' in bench.split("SKILL_INSTALL_LOCATIONS =", 1)[1], "helper tuple no longer contains the repo-root path literal"
assert ".github/skills/SKILL.md, .claude/skills/quality-playbook/SKILL.md, or SKILL.md" in runner, "warning text no longer shows the stale three-path message"
print("probe-8 ok: repository-side helper tuple and warning text still diverge from the canonical four-path order")
PY

python3 - <<'PY'
from pathlib import Path

repo = Path(".")
claude_agent = (repo / "agents" / "quality-playbook-claude.agent.md").read_text(encoding="utf-8")
assert "3. `.github/skills/quality-playbook/SKILL.md`" in claude_agent, "Claude orchestrator no longer lists nested Copilot third"
assert "4. `.github/skills/SKILL.md`" in claude_agent, "Claude orchestrator no longer lists flat Copilot fourth"
print("probe-9 ok: Claude orchestrator still reverses the two Copilot fallback positions")
PY
