#!/bin/bash
# Triage verification probes — executable evidence for audit findings
# Generated by Quality Playbook v1.4.0 — 2026-04-15

set -uo pipefail
PASS=0
FAIL=0

# Probe SA-06: "five strategies" vs four (NET-NEW — REQ-002)
LINE210=$(sed -n '210p' SKILL.md)
STRAT_COUNT=$(grep -c '^## Strategy:' references/iteration.md)
LINE1879=$(sed -n '1879p' SKILL.md)
if echo "$LINE210" | grep -q 'five strategies' && [ "$STRAT_COUNT" -eq 4 ] && echo "$LINE1879" | grep -q 'four'; then
    echo "CONFIRMED SA-06: SKILL.md line 210 says 'five strategies'; iteration.md defines $STRAT_COUNT; line 1879 says 'four'"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED SA-06: No inconsistency found"
    PASS=$((PASS + 1))
fi

# Probe SA-14: verification.md Phase 7 reference (NET-NEW — REQ-002)
LINE75=$(sed -n '75p' references/verification.md)
PLAN_PHASE7=$(sed -n '12,31p' SKILL.md | grep -ci 'phase 7' || true)
PLAN_PHASE7=${PLAN_PHASE7:-0}
if echo "$LINE75" | grep -qi 'phase 7' && [ "$PLAN_PHASE7" -eq 0 ]; then
    echo "CONFIRMED SA-14: verification.md line 75 references Phase 7; plan overview has 0 mentions"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED SA-14: No Phase 7 reference issue"
    PASS=$((PASS + 1))
fi

# Probe SA-15: verification.md hardcoded path (NET-NEW — REQ-003)
LINE172=$(sed -n '172p' references/verification.md)
if echo "$LINE172" | grep -q '\.github/skills/SKILL\.md'; then
    HAS_CLAUDE=$(echo "$LINE172" | grep -c '\.claude/skills' || true)
    HAS_CLAUDE=${HAS_CLAUDE:-0}
    if [ "$HAS_CLAUDE" -eq 0 ]; then
        echo "CONFIRMED SA-15: verification.md line 172 hardcodes '.github/skills/SKILL.md' with no Claude Code fallback"
        FAIL=$((FAIL + 1))
    else
        echo "REJECTED SA-15: Line includes Claude Code fallback"
        PASS=$((PASS + 1))
    fi
else
    echo "REJECTED SA-15: Line does not hardcode .github/skills/SKILL.md"
    PASS=$((PASS + 1))
fi

# Probe BUG-001 (confirmation): tdd_verified in Example 1
if grep -q '"tdd_verified"' SKILL.md; then
    echo "CONFIRMED BUG-001: SKILL.md contains 'tdd_verified' (line $(grep -n '"tdd_verified"' SKILL.md | head -1 | cut -d: -f1))"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED BUG-001: No 'tdd_verified' in SKILL.md"
    PASS=$((PASS + 1))
fi

# Probe BUG-002 (confirmation): Phase 7 not in plan overview
PLAN_P7=$(sed -n '12,31p' SKILL.md | grep -ci 'phase 7' || true)
PLAN_P7=${PLAN_P7:-0}
BODY_P7=$(grep -c 'Phase 7' SKILL.md || true)
BODY_P7=${BODY_P7:-0}
if [ "$PLAN_P7" -eq 0 ] && [ "$BODY_P7" -gt 0 ]; then
    echo "CONFIRMED BUG-002: Phase 7 in body ($BODY_P7 occurrences) but not in plan overview"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED BUG-002"
    PASS=$((PASS + 1))
fi

# Probe BUG-003 (confirmation): hardcoded reference paths
HC_COUNT=$(grep -c '\.github/skills/references/' SKILL.md || true)
HC_COUNT=${HC_COUNT:-0}
if [ "$HC_COUNT" -gt 0 ]; then
    echo "CONFIRMED BUG-003: $HC_COUNT hardcoded .github/skills/references/ paths in SKILL.md"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED BUG-003"
    PASS=$((PASS + 1))
fi

# Probe BUG-004 (confirmation): gate does not validate TDD log status tags
# The gate section (lines 277-322) checks -f (file existence), not status tag content
STATUS_CHECK=$(sed -n '277,322p' quality_gate.sh | grep -c 'head\|sed.*1p\|awk.*NR==1\|read.*line' || true)
STATUS_CHECK=${STATUS_CHECK:-0}
if [ "$STATUS_CHECK" -eq 0 ]; then
    echo "CONFIRMED BUG-004: Gate does not read or validate TDD log first-line status tags"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED BUG-004: Gate appears to validate status tags"
    PASS=$((PASS + 1))
fi

# Probe BUG-005 (confirmation): gate missing CONTRACTS.md check
if grep -q 'CONTRACTS.md' quality_gate.sh; then
    echo "REJECTED BUG-005: Gate checks CONTRACTS.md"
    PASS=$((PASS + 1))
else
    echo "CONFIRMED BUG-005: CONTRACTS.md not checked by gate"
    FAIL=$((FAIL + 1))
fi

# Probe BUG-006 (confirmation): AGENTS.md missing Claude path
if grep -q '\.claude/skills' AGENTS.md; then
    echo "REJECTED BUG-006: AGENTS.md has Claude Code path"
    PASS=$((PASS + 1))
else
    echo "CONFIRMED BUG-006: AGENTS.md missing .claude/skills path"
    FAIL=$((FAIL + 1))
fi

# Probe BUG-008 (confirmation): gate missing total and verified summary checks
CHECKS_TOTAL=$(grep -c '"total"' quality_gate.sh || true)
CHECKS_TOTAL=${CHECKS_TOTAL:-0}
CHECKS_VERIFIED=$(grep -c '"verified"' quality_gate.sh || true)
CHECKS_VERIFIED=${CHECKS_VERIFIED:-0}
if [ "$CHECKS_TOTAL" -eq 0 ] && [ "$CHECKS_VERIFIED" -eq 0 ]; then
    echo "CONFIRMED BUG-008: Gate does not check 'total' or 'verified' summary keys"
    FAIL=$((FAIL + 1))
else
    echo "REJECTED BUG-008"
    PASS=$((PASS + 1))
fi

# Probe BUG-013 (confirmation): TOOLKIT.md missing Claude path
if grep -q '\.claude/skills' ai_context/TOOLKIT.md; then
    echo "REJECTED BUG-013: TOOLKIT.md has Claude Code path"
    PASS=$((PASS + 1))
else
    echo "CONFIRMED BUG-013: TOOLKIT.md missing .claude/skills path"
    FAIL=$((FAIL + 1))
fi

echo ""
echo "=== Triage Probes Summary ==="
echo "Confirmed (FAIL — bug exists): $FAIL"
echo "Rejected (PASS — finding false): $PASS"
