#!/bin/bash
# Triage verification probes for spec audit findings
# Each probe produces executable evidence for confirmation or rejection.
#
# Generated by Quality Playbook v1.4.0 — 2026-04-15

set -uo pipefail
PASS=0
FAIL_COUNT=0

probe_pass() { echo "  PROBE PASS: $1"; PASS=$((PASS + 1)); }
probe_fail() { echo "  PROBE FAIL: $1"; FAIL_COUNT=$((FAIL_COUNT + 1)); }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}/../.."

echo "=== Spec Audit Triage Probes ==="
echo ""

# --- SA-01: Required artifacts use warn() instead of fail() ---
echo "[SA-01] Confirm: 5 required artifacts use warn() not fail()"
# Verify that lines 117-122 use warn(), not fail()
warn_count=$(sed -n '117,122p' "${REPO_ROOT}/quality_gate.sh" | grep -c "warn " || true)
if [ "$warn_count" -ge 1 ]; then
    probe_pass "SA-01 confirmed: lines 117-122 contain warn() calls (count: ${warn_count})"
else
    probe_fail "SA-01 not confirmed: expected warn() calls at lines 117-122"
fi

# --- SA-02: test_functional detection incomplete ---
echo "[SA-02] Confirm: gate only checks test_functional.* pattern"
pattern_count=$(grep -c "FunctionalSpec\|FunctionalTest\|functional\.test\." "${REPO_ROOT}/quality_gate.sh" || true)
if [ "$pattern_count" -eq 0 ]; then
    probe_pass "SA-02 confirmed: gate has 0 references to alternative test file names"
else
    probe_fail "SA-02 not confirmed: found ${pattern_count} alternative pattern references"
fi

# --- SA-03: AGENTS.md not checked ---
echo "[SA-03] Confirm: no AGENTS.md check in quality_gate.sh"
agents_count=$(grep -c "AGENTS" "${REPO_ROOT}/quality_gate.sh" || true)
if [ "$agents_count" -eq 0 ]; then
    probe_pass "SA-03 confirmed: 'AGENTS' appears 0 times in quality_gate.sh"
else
    probe_fail "SA-03 not confirmed: 'AGENTS' appears ${agents_count} times"
fi

# --- SA-04: eval injection ---
echo "[SA-04] Confirm: eval used with user-supplied repo_dir"
eval_count=$(grep -c 'eval.*repo_dir' "${REPO_ROOT}/quality_gate.sh" || true)
if [ "$eval_count" -gt 0 ]; then
    probe_pass "SA-04 confirmed: eval with repo_dir found ${eval_count} times"
else
    probe_fail "SA-04 not confirmed: no eval with repo_dir found"
fi

# --- SA-05: Phase 6 numbering error ---
echo "[SA-05] Confirm: Phase numbering jumps from 2 to 6"
phase_sequence=$(grep -n "^### Phase" "${REPO_ROOT}/references/review_protocols.md" | tail -3 | grep -oE "Phase [0-9]+" | tr '\n' ',' || true)
if echo "$phase_sequence" | grep -q "Phase 6"; then
    probe_pass "SA-05 confirmed: Phase sequence includes 'Phase 6' (sequence: ${phase_sequence})"
else
    probe_fail "SA-05 not confirmed: no Phase 6 found"
fi

# --- SA-06: Dangling BUG-005 reference ---
echo "[SA-06] Confirm: BUG-005 reference at line 116 has no matching documentation"
# Count BUG-005 references outside of quality/ artifacts (which are generated, not source)
source_bug005=$(grep -rn "BUG-005" "${REPO_ROOT}/quality_gate.sh" | wc -l | tr -d ' ')
doc_bug005=$(grep -rn "^### BUG-005" "${REPO_ROOT}" --include="*.md" 2>/dev/null | grep -v "quality/" | wc -l | tr -d ' ')
if [ "$source_bug005" -gt 0 ] && [ "$doc_bug005" -eq 0 ]; then
    probe_pass "SA-06 confirmed: BUG-005 referenced in gate (${source_bug005}x) but no source-level documentation (0 headings outside quality/)"
else
    probe_fail "SA-06 not confirmed"
fi

# --- SA-07: verification.md benchmark 40 file list incomplete ---
echo "[SA-07] Confirm: benchmark 40 missing required artifacts"
# Check if benchmark 40 mentions CONTRACTS.md
b40_contracts=$(grep -A5 "### 40\." "${REPO_ROOT}/references/verification.md" | grep -c "CONTRACTS" || true)
if [ "$b40_contracts" -eq 0 ]; then
    probe_pass "SA-07 confirmed: benchmark 40 does not mention CONTRACTS.md (or other required artifacts)"
else
    probe_fail "SA-07 not confirmed: benchmark 40 mentions CONTRACTS.md"
fi

# --- SA-08: Version detection path asymmetry ---
echo "[SA-08] Confirm: global detection has more paths than per-repo detection"
global_paths=$(sed -n '61p' "${REPO_ROOT}/quality_gate.sh" | grep -oE '"[^"]*SKILL\.md"' | wc -l | tr -d ' ')
perrepo_paths=$(sed -n '581p' "${REPO_ROOT}/quality_gate.sh" | grep -oE '"[^"]*SKILL\.md"' | wc -l | tr -d ' ')
if [ "$global_paths" -gt "$perrepo_paths" ]; then
    probe_pass "SA-08 confirmed: global detection has ${global_paths} paths, per-repo has ${perrepo_paths}"
else
    probe_fail "SA-08 not confirmed: global=${global_paths}, per-repo=${perrepo_paths}"
fi

# --- SA-09: JSON helper false-match risk (design choice) ---
echo "[SA-09] Reject as design choice: JSON helpers use simple grep"
json_has_key_line=$(sed -n '77p' "${REPO_ROOT}/quality_gate.sh")
if echo "$json_has_key_line" | grep -q 'grep -q'; then
    probe_pass "SA-09 confirmed as design choice: json_has_key uses simple grep at line 77"
else
    probe_fail "SA-09: unexpected json_has_key implementation"
fi

# --- SA-10: No lower-bound date validation (design choice) ---
echo "[SA-10] Reject as design choice: no lower bound required by spec"
lower_bound=$(grep -c "1970\|lower.bound\|too.old\|minimum.date\|before.*19" "${REPO_ROOT}/quality_gate.sh" || true)
if [ "$lower_bound" -eq 0 ]; then
    probe_pass "SA-10 confirmed as design choice: no lower-bound date check (spec does not require one)"
else
    probe_fail "SA-10: found lower-bound date check (count: ${lower_bound})"
fi

echo ""
echo "=== Results: ${PASS} PASS, ${FAIL_COUNT} FAIL ==="
[ "$FAIL_COUNT" -eq 0 ] && exit 0 || exit 1
