#!/bin/bash
# Generated by Quality Playbook v1.4.1 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-16 · Project: quality-playbook
#
# Regression tests for confirmed bugs from Phase 3 code review.
#
# Skip guards: each test checks for BUG_SKIP_NNN env var (default: 1 = skip).
# To run a specific test for red-phase verification:
#   BUG_SKIP_H1=0 bash quality/test_regression.sh test_BUG_H1_json_has_key_false_positive
# To run all tests with skip guards disabled:
#   BUG_SKIP_H1=0 BUG_SKIP_H2=0 BUG_SKIP_M3=0 BUG_SKIP_M4=0 \
#   BUG_SKIP_M5=0 BUG_SKIP_L6=0 BUG_SKIP_L7=0 \
#   BUG_SKIP_M8=0 BUG_SKIP_L9=0 BUG_SKIP_L10=0 BUG_SKIP_L11=0 \
#   bash quality/test_regression.sh
#
# Phase 4 spec audit additions (BUG_SKIP_M8, L9, L10, L11):
#   BUG_SKIP_M8=0 — nullglob ls-glob counting (quality_gate.sh:152-153,331,567-568,595)
#   BUG_SKIP_L9=0 — auditor naming inconsistency (SKILL.md:1548 vs RUN_SPEC_AUDIT.md:143)
#   BUG_SKIP_L10=0 — recheck schema_version "1.0" vs "1.1" (SKILL.md:1965)
#   BUG_SKIP_L11=0 — two incompatible tdd-results.json templates (SKILL.md:135 vs 1385)
#
# All tests are skip-guarded by default to avoid failing CI before fixes land.
# Remove skip guards only after applying the corresponding fix patch.

set -uo pipefail

PASS=0
FAIL=0
SKIP=0

run_test() {
    local name="$1"
    echo ""
    echo "  TEST: $name"
    if "$name"; then
        echo "  RESULT: PASS"
        PASS=$((PASS + 1))
    else
        echo "  RESULT: FAIL"
        FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
# BUG-H1: json_has_key matches keys inside string values (false positive)
#
# The bug: json_has_key uses `grep -q "\"key\""` without requiring a colon.
# A JSON file where "id" appears only inside a string value returns true.
# [BUG from quality/code_reviews/pass1_structural.md, line 7]
# Skip guard: set BUG_SKIP_H1=0 to enable
# Fix: quality/patches/BUG-H1-fix.patch
# ---------------------------------------------------------------------------
test_BUG_H1_json_has_key_false_positive() {
    if [ "${BUG_SKIP_H1:-1}" = "1" ]; then
        echo "  SKIP: BUG-H1 skip guard active (set BUG_SKIP_H1=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # Create a JSON file where "id" appears only as a STRING VALUE, NOT as a key.
    # The bug: json_has_key "id" matches any occurrence of "id" in the file,
    # including when "id" is a VALUE (e.g., "field_type": "id").
    # This causes false-positive key detection — the gate thinks "id" is present
    # as a key when it is only a value in a different field.
    local tmpfile
    tmpfile=$(mktemp /tmp/bug_h1_test.XXXXXX.json)
    cat > "$tmpfile" <<'EOF'
{
  "field_type": "id",
  "schema_version": "1.1",
  "project": "quality-playbook"
}
EOF
    # Note: "id" appears as a VALUE ("id") not as a key ("id": ...).
    # json_has_key "id" should return false (exit 1) — "id" is not a JSON key here.
    # Buggy behavior: grep -q "\"id\"" matches the VALUE "id" and returns true.

    # Reproduce the buggy json_has_key from quality_gate.sh:75-78
    json_has_key_buggy() {
        local file="$1" key="$2"
        grep -q "\"${key}\"" "$file" 2>/dev/null
    }

    # Expected: json_has_key "id" should return false (1) — "id" is not a key here
    # Bug behavior: returns true (0) because "id" appears inside the string value
    local result=0
    if json_has_key_buggy "$tmpfile" "id"; then
        echo "  BUG CONFIRMED: json_has_key returned true for 'id' appearing only in string value"
        echo "  JSON content: $(cat "$tmpfile")"
        result=1
    else
        echo "  BUG FIXED: json_has_key correctly returned false for 'id' in string value only"
    fi

    rm -f "$tmpfile"
    return $result
}

# ---------------------------------------------------------------------------
# BUG-H2: Unquoted array expansion corrupts repository paths containing spaces
#
# The bug: REPO_DIRS=(${resolved[@]+"${resolved[@]}"}) at line 697 is unquoted.
# Word-splitting turns "/path/with spaces/repo" into multiple elements.
# [BUG from quality/code_reviews/pass1_structural.md, line ~50]
# Skip guard: set BUG_SKIP_H2=0 to enable
# Fix: quality/patches/BUG-H2-fix.patch
# ---------------------------------------------------------------------------
test_BUG_H2_array_expansion_corrupts_spaces() {
    if [ "${BUG_SKIP_H2:-1}" = "1" ]; then
        echo "  SKIP: BUG-H2 skip guard active (set BUG_SKIP_H2=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # Simulate the buggy array reconstruction from quality_gate.sh:697
    local resolved=("/Users/joe/My Projects/my-repo")

    # Buggy reconstruction (unquoted outer expansion — from quality_gate.sh:697)
    local REPO_DIRS_BUGGY
    REPO_DIRS_BUGGY=(${resolved[@]+"${resolved[@]}"})

    # Fixed reconstruction (quoted outer expansion — the fix)
    local REPO_DIRS_FIXED
    REPO_DIRS_FIXED=("${resolved[@]+"${resolved[@]}"}")

    local buggy_count="${#REPO_DIRS_BUGGY[@]}"
    local fixed_count="${#REPO_DIRS_FIXED[@]}"

    echo "  Buggy reconstruction: ${buggy_count} element(s)"
    echo "  Fixed reconstruction: ${fixed_count} element(s)"

    if [ "$buggy_count" -ne 1 ]; then
        echo "  BUG CONFIRMED: path with spaces split into ${buggy_count} elements (expected 1)"
        echo "  Elements: ${REPO_DIRS_BUGGY[*]}"
        # Show that the fix works
        if [ "$fixed_count" -eq 1 ] && [ "${REPO_DIRS_FIXED[0]}" = "/Users/joe/My Projects/my-repo" ]; then
            echo "  Fix is correct: quoted expansion preserves path as single element"
        fi
        return 1  # Test FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED or not triggered: path preserved as single element"
        echo "  Note: word-splitting behavior may vary by bash version/IFS setting"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-M3: Phase 2 entry gate enforces only 6 of 12 Phase 1 checks
#
# The bug: Phase 2 entry gate (SKILL.md:897-904) checks for 6 section titles
# only; checks 2, 3, 5, 8, 10, 12 from Phase 1 gate are not backstopped.
# [BUG from quality/code_reviews/pass1_structural.md]
# Skip guard: set BUG_SKIP_M3=0 to enable
# Fix: quality/patches/BUG-M3-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M3_phase2_gate_missing_checks() {
    if [ "${BUG_SKIP_M3:-1}" = "1" ]; then
        echo "  SKIP: BUG-M3 skip guard active (set BUG_SKIP_M3=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local skill_md="${SKILL_MD_PATH:-SKILL.md}"

    if [ ! -f "$skill_md" ]; then
        echo "  SKIP: SKILL.md not found at $skill_md (set SKILL_MD_PATH=path/to/SKILL.md)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # Count numbered checks in Phase 1 completion gate section
    local phase1_checks
    phase1_checks=$(awk '/Phase 1 completion gate \(mandatory/,/Do not begin Phase 2/' "$skill_md" \
        | grep -cE '^[0-9]+\.' || true)
    phase1_checks="${phase1_checks:-0}"

    # Count numbered items in Phase 2 entry gate section
    local phase2_checks
    phase2_checks=$(awk '/Phase 2 entry gate \(mandatory — HARD STOP\)/,/If the file does not exist/' "$skill_md" \
        | grep -cE '^[0-9]+\.' || true)
    phase2_checks="${phase2_checks:-0}"

    echo "  Phase 1 completion gate: ${phase1_checks} numbered checks"
    echo "  Phase 2 entry gate: ${phase2_checks} numbered checks"

    if [ "${phase1_checks}" -le "${phase2_checks}" ]; then
        echo "  BUG FIXED: Phase 2 gate now enforces all Phase 1 checks"
        return 0
    else
        local missing=$((phase1_checks - phase2_checks))
        echo "  BUG CONFIRMED: Phase 2 gate has ${missing} fewer checks than Phase 1 gate"
        echo "  Missing: checks 2, 3, 5, 8, 10, 12 (depth, FULL patterns, ensemble balance)"
        return 1  # Test FAILS on unpatched code (red phase)
    fi
}

# ---------------------------------------------------------------------------
# BUG-M4: test_regression.* not checked by gate despite artifact contract
#
# The bug: quality_gate.sh checks patches but not test_regression.* file.
# Artifact contract at SKILL.md:88-119 requires test_regression.* when bugs exist.
# [BUG from quality/code_reviews/pass1_structural.md]
# Skip guard: set BUG_SKIP_M4=0 to enable
# Fix: quality/patches/BUG-M4-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M4_gate_missing_regression_file_check() {
    if [ "${BUG_SKIP_M4:-1}" = "1" ]; then
        echo "  SKIP: BUG-M4 skip guard active (set BUG_SKIP_M4=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local gate="${GATE_PATH:-quality_gate.sh}"

    if [ ! -f "$gate" ]; then
        echo "  SKIP: quality_gate.sh not found at $gate (set GATE_PATH=path/to/quality_gate.sh)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # Set up a minimal test environment: bugs present but no test_regression.* file
    local tmpdir
    tmpdir=$(mktemp -d /tmp/bug_m4_test.XXXXXX)
    local q="${tmpdir}/quality"
    mkdir -p "${q}/patches" "${q}/results" "${q}/code_reviews" "${q}/spec_audits"

    cat > "${q}/BUGS.md" <<'EOF'
# Bug Report

### BUG-001
Description: test bug for BUG-M4 regression test
Severity: LOW
EOF

    # Minimal required artifacts (without test_regression.*)
    for f in REQUIREMENTS.md QUALITY.md PROGRESS.md COVERAGE_MATRIX.md \
              COMPLETENESS_REPORT.md CONTRACTS.md RUN_CODE_REVIEW.md \
              RUN_SPEC_AUDIT.md RUN_INTEGRATION_TESTS.md RUN_TDD_TESTS.md \
              EXPLORATION.md; do
        touch "${q}/${f}"
    done
    touch "${q}/test_functional.sh"
    touch "${tmpdir}/AGENTS.md"
    echo "review" > "${q}/code_reviews/review.md"
    echo "triage" > "${q}/spec_audits/triage.md"
    echo "auditor" > "${q}/spec_audits/auditor1.md"
    touch "${q}/spec_audits/triage_probes.sh"
    # Add version stamp to PROGRESS.md so the version check doesn't abort early
    echo "Skill version: 1.4.1" >> "${q}/PROGRESS.md"
    echo "## Terminal Gate Verification" >> "${q}/PROGRESS.md"

    # Run the gate
    local gate_output gate_exit
    gate_output=$(bash "$gate" --general "$tmpdir" 2>&1 || true)
    gate_exit=$?

    rm -rf "$tmpdir"

    # Check if gate output mentions test_regression with a FAIL
    if echo "$gate_output" | grep -qiE "FAIL.*test_regression|test_regression.*FAIL|FAIL.*test_regression\.\*|test_regression.*missing"; then
        echo "  BUG FIXED: gate correctly FAILs for missing test_regression.*"
        return 0
    fi

    echo "  BUG CONFIRMED: gate did not FAIL for missing test_regression.* when bug_count > 0"
    echo "  Gate exit: $gate_exit"
    echo "  Gate output (last 20 lines):"
    echo "$gate_output" | tail -20 | sed 's/^/    /'
    return 1  # Test FAILS on unpatched code (red phase)
}

# ---------------------------------------------------------------------------
# BUG-M5: Phase 0b skips when previous_runs/ exists but is empty
#
# The bug: Phase 0b activation says "previous_runs/ does not exist" but
# Phase 0a only runs when it exists AND contains artifacts. Empty dir: gap.
# [BUG from quality/code_reviews/pass1_structural.md]
# Skip guard: set BUG_SKIP_M5=0 to enable
# Fix: quality/patches/BUG-M5-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M5_phase0b_skips_on_empty_previous_runs() {
    if [ "${BUG_SKIP_M5:-1}" = "1" ]; then
        echo "  SKIP: BUG-M5 skip guard active (set BUG_SKIP_M5=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local skill_md="${SKILL_MD_PATH:-SKILL.md}"

    if [ ! -f "$skill_md" ]; then
        echo "  SKIP: SKILL.md not found at $skill_md (set SKILL_MD_PATH=path/to/SKILL.md)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # Extract Phase 0b activation condition
    local phase0b_condition
    phase0b_condition=$(grep -A5 'Phase 0b: Sibling-Run' "$skill_md" \
        | grep -E 'runs only if|This step runs' | head -1 || true)

    echo "  Phase 0b activation: $phase0b_condition"

    # Check if the fixed condition includes empty-directory case
    if echo "$phase0b_condition" | grep -qiE 'OR.*empty|empty.*OR|no conformant|is empty'; then
        echo "  BUG FIXED: Phase 0b condition covers empty previous_runs/ case"
        return 0
    fi

    # Bug present: activation says only "does not exist" without OR clause for empty
    if echo "$phase0b_condition" | grep -q "does not exist"; then
        echo "  BUG CONFIRMED: Phase 0b says 'does not exist' — empty dir creates gap"
        echo "  Gap: empty previous_runs/ causes both Phase 0a AND 0b to skip silently"
        return 1  # Test FAILS on unpatched code (red phase)
    else
        echo "  INCONCLUSIVE: Could not parse Phase 0b activation condition"
        echo "  Manual verification required at SKILL.md lines 295-297"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# BUG-L6: json_str_val returns empty for non-string values
#
# The bug: json_str_val() returns "" for numeric/bool values.
# Caller at line 236 reports "missing" when the field exists as wrong type.
# [BUG from quality/code_reviews/pass1_structural.md, line ~25]
# Skip guard: set BUG_SKIP_L6=0 to enable
# Fix: quality/patches/BUG-L6-fix.patch
# ---------------------------------------------------------------------------
test_BUG_L6_json_str_val_non_string_empty() {
    if [ "${BUG_SKIP_L6:-1}" = "1" ]; then
        echo "  SKIP: BUG-L6 skip guard active (set BUG_SKIP_L6=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # Reproduce the buggy json_str_val from quality_gate.sh:81-85
    json_str_val_buggy() {
        local file="$1" key="$2"
        grep -o "\"${key}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" 2>/dev/null \
            | head -1 | sed 's/.*: *"\([^"]*\)"/\1/'
    }

    local tmpfile
    tmpfile=$(mktemp /tmp/bug_l6_test.XXXXXX.json)
    cat > "$tmpfile" <<'EOF'
{
  "schema_version": 1.1,
  "skill_version": "1.4.1",
  "date": "2026-04-16"
}
EOF

    local result
    result=$(json_str_val_buggy "$tmpfile" "schema_version")

    rm -f "$tmpfile"

    if [ -z "$result" ]; then
        echo "  BUG CONFIRMED: json_str_val returned empty for number-typed 'schema_version'"
        echo "  Caller would report: \"schema_version is 'missing', expected '1.1'\""
        echo "  Actual problem: field exists but is a number, not a string"
        return 1  # Test FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: json_str_val returned '${result}' for number-typed schema_version"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L7: Version number hardcoded in 8+ SKILL.md locations without check
#
# The bug: No mechanical check enforces that all SKILL.md version strings
# match the frontmatter. Current state is consistent (all 1.4.1) but
# a version bump could leave stale inline occurrences undetected.
# [BUG from quality/code_reviews/pass1_structural.md]
# Skip guard: set BUG_SKIP_L7=0 to enable
# No fix patch — fix is integrating this test into quality_gate.sh or CI
# ---------------------------------------------------------------------------
test_BUG_L7_version_string_consistency() {
    if [ "${BUG_SKIP_L7:-1}" = "1" ]; then
        echo "  SKIP: BUG-L7 skip guard active (set BUG_SKIP_L7=0 to run)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local skill_md="${SKILL_MD_PATH:-SKILL.md}"

    if [ ! -f "$skill_md" ]; then
        echo "  SKIP: SKILL.md not found at $skill_md (set SKILL_MD_PATH=path/to/SKILL.md)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local frontmatter_version
    frontmatter_version=$(grep -m1 'version:' "$skill_md" | sed 's/.*version: *//' | tr -d ' ')

    if [ -z "$frontmatter_version" ]; then
        echo "  SKIP: Could not extract frontmatter version"
        SKIP=$((SKIP + 1))
        return 0
    fi

    echo "  Frontmatter version: $frontmatter_version"

    # Find all X.Y.Z version strings that differ from frontmatter
    local stale_count
    stale_count=$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' "$skill_md" \
        | grep -cv "^${frontmatter_version}$" || true)

    if [ "${stale_count:-0}" -gt 0 ]; then
        echo "  BUG CONFIRMED: ${stale_count} version string(s) differ from frontmatter '${frontmatter_version}'"
        grep -nE '[0-9]+\.[0-9]+\.[0-9]+' "$skill_md" \
            | grep -v "${frontmatter_version}" | head -10 | sed 's/^/    /'
        return 1
    else
        local total_count
        total_count=$(grep -cE '[0-9]+\.[0-9]+\.[0-9]+' "$skill_md" || true)
        echo "  All ${total_count} version string(s) match frontmatter '${frontmatter_version}'"
        echo "  NOTE: BUG-L7 is a LATENT risk — this test only catches stale versions AFTER a bump."
        echo "        The real fix is integrating this check into quality_gate.sh or CI."
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-M8: Systemic nullglob vulnerability in ls-glob counting operations
#
# The bug: Multiple artifact-counting operations use ls ${q}/path/*glob* | wc -l
# Under nullglob (active by default in zsh/macOS), unmatched globs expand to empty,
# causing ls to list the current directory. wc -l counts that listing, producing
# nonzero counts even when no matching files exist. The gate incorrectly passes.
# Affected lines: 152-153 (spec_audits), 331 (fix patch check), 567-568 (patches),
# 595 (writeups)
# [BUG from Phase 4 Spec Audit — all three auditors]
# Skip guard: set BUG_SKIP_M8=0 to enable
# Fix: quality/patches/BUG-M8-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M8_nullglob_ls_counting() {
    if [ "${BUG_SKIP_M8:-1}" = "1" ]; then
        echo "  SKIP: BUG-M8 skip guard active (set BUG_SKIP_M8=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local gate="${GATE_PATH:-quality_gate.sh}"

    if [ ! -f "$gate" ]; then
        echo "  SKIP: quality_gate.sh not found at $gate (set GATE_PATH=...)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: Verify that unquoted ls-glob counting patterns exist in the gate
    # Line 567: reg_patch_count=$(ls ${q}/patches/BUG-*-regression*.patch ...)
    # Line 331: if ls ${q}/patches/${bid}-fix*.patch ...
    # These patterns use unquoted globs that are vulnerable to nullglob

    # Check for the specific vulnerable pattern at line 567
    local line567
    line567=$(sed -n '567p' "$gate")
    local line331
    line331=$(sed -n '331p' "$gate")

    local found_vulnerable=false
    if echo "$line567" | grep -q 'ls \${q}/patches/BUG-\*-regression\*'; then
        found_vulnerable=true
        echo "  Line 567 (vulnerable): $line567"
    fi
    if echo "$line331" | grep -q 'ls \${q}/patches/\${bid}-fix\*'; then
        found_vulnerable=true
        echo "  Line 331 (vulnerable): $line331"
    fi

    if [ "$found_vulnerable" = true ]; then
        echo "  BUG CONFIRMED: Unquoted ls-glob counting patterns present — vulnerable to nullglob"
        echo "  Under nullglob, ls with no glob matches lists current dir, wc -l returns wrong count"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: ls-glob counting patterns replaced with nullglob-safe find/count"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L9: Auditor report naming inconsistency across SKILL.md, RUN_SPEC_AUDIT.md
#
# The bug: Three incompatible naming formats specified:
# SKILL.md:1548 → YYYY-MM-DD-auditor-N.md
# RUN_SPEC_AUDIT.md:143 → auditor_<model>_<date>.md
# references/spec_audit.md → YYYY-MM-DD-[model].md
# [BUG from Phase 4 Spec Audit — Auditor A]
# Skip guard: set BUG_SKIP_L9=0 to enable
# Fix: (no patch — fix is standardizing naming in SKILL.md and RUN_SPEC_AUDIT.md template)
# ---------------------------------------------------------------------------
test_BUG_L9_auditor_naming_inconsistency() {
    if [ "${BUG_SKIP_L9:-1}" = "1" ]; then
        echo "  SKIP: BUG-L9 skip guard active (set BUG_SKIP_L9=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local skill_md="${SKILL_MD_PATH:-SKILL.md}"
    local run_spec_audit="quality/RUN_SPEC_AUDIT.md"

    if [ ! -f "$skill_md" ]; then
        echo "  SKIP: SKILL.md not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: Two different naming formats coexist
    # SKILL.md line 1548 specifies: YYYY-MM-DD-auditor-N.md
    local skill_format
    skill_format=$(grep -n 'YYYY-MM-DD-auditor-N' "$skill_md" | head -1)

    # RUN_SPEC_AUDIT.md line 143 specifies: auditor_<model>_<date>.md
    local run_format=""
    if [ -f "$run_spec_audit" ]; then
        run_format=$(grep -n 'auditor_<model>' "$run_spec_audit" | head -1)
    fi

    if [ -n "$skill_format" ] && [ -n "$run_format" ]; then
        echo "  BUG CONFIRMED: Two incompatible auditor naming formats exist"
        echo "  SKILL.md (Phase 4 instructions): $skill_format"
        echo "  RUN_SPEC_AUDIT.md: $run_format"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED or formats unified"
        echo "  SKILL.md format: '${skill_format:-not found}'"
        echo "  RUN_SPEC_AUDIT.md format: '${run_format:-not found}'"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L10: Recheck mode uses schema_version "1.0" while all other sidecars use "1.1"
#
# The bug: SKILL.md recheck template (line 1965) specifies schema_version "1.0"
# while tdd-results.json (line 128) and integration-results.json (line 156)
# use schema_version "1.1". No migration note explains the discrepancy.
# [BUG from Phase 4 Spec Audit — Auditors A and B]
# Skip guard: set BUG_SKIP_L10=0 to enable
# Fix: (no patch — fix is updating recheck template or documenting the intent)
# ---------------------------------------------------------------------------
test_BUG_L10_recheck_schema_version_inconsistency() {
    if [ "${BUG_SKIP_L10:-1}" = "1" ]; then
        echo "  SKIP: BUG-L10 skip guard active (set BUG_SKIP_L10=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local skill_md="${SKILL_MD_PATH:-SKILL.md}"

    if [ ! -f "$skill_md" ]; then
        echo "  SKIP: SKILL.md not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: Both schema versions exist in SKILL.md
    local recheck_schema
    recheck_schema=$(grep -n '"schema_version": "1\.0"' "$skill_md" | head -1)
    local main_schema
    main_schema=$(grep -n '"schema_version": "1\.1"' "$skill_md" | head -1)

    if [ -n "$recheck_schema" ] && [ -n "$main_schema" ]; then
        echo "  BUG CONFIRMED: SKILL.md contains both schema_version '1.0' and '1.1'"
        echo "  Recheck template (1.0): $recheck_schema"
        echo "  TDD/integration template (1.1): $main_schema"
        echo "  No migration note explains the version discrepancy"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: schema versions unified (or recheck schema updated)"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L11: Two incompatible tdd-results.json templates in SKILL.md
#
# The bug: Artifact contract section (line ~135) uses "UC-03: Description..." format
# for the "requirement" field; Phase 5 File 7 section (line ~1385) uses "REQ-003".
# Agents see different expectations for the same required JSON field.
# [BUG from Phase 4 Spec Audit — Auditors A and B]
# Skip guard: set BUG_SKIP_L11=0 to enable
# Fix: (no patch — fix is standardizing the templates)
# ---------------------------------------------------------------------------
test_BUG_L11_tdd_results_two_incompatible_templates() {
    if [ "${BUG_SKIP_L11:-1}" = "1" ]; then
        echo "  SKIP: BUG-L11 skip guard active (set BUG_SKIP_L11=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local skill_md="${SKILL_MD_PATH:-SKILL.md}"

    if [ ! -f "$skill_md" ]; then
        echo "  SKIP: SKILL.md not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: Template 1 (artifact contract ~line 135) uses UC-format
    local template1_uc
    template1_uc=$(grep -n '"requirement":.*UC-[0-9][0-9]:' "$skill_md" | head -1)

    # Template 2 (Phase 5 ~line 1385) uses REQ-format
    local template2_req
    template2_req=$(grep -n '"requirement": "REQ-[0-9]' "$skill_md" | head -1)

    if [ -n "$template1_uc" ] && [ -n "$template2_req" ]; then
        echo "  BUG CONFIRMED: Two incompatible 'requirement' field formats in SKILL.md"
        echo "  Template 1 (artifact contract, UC-format): $template1_uc"
        echo "  Template 2 (Phase 5, REQ-format): $template2_req"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED or templates unified"
        echo "  UC-format: '${template1_uc:-not found}'"
        echo "  REQ-format: '${template2_req:-not found}'"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-M12: ls-glob in test file extension detection (quality_gate.sh:479)
#
# The bug: `func_test=$(ls ${q}/test_functional.* 2>/dev/null | head -1)` uses
# ls-glob pattern vulnerable to nullglob: under zsh nullglob, unmatched glob
# expands to empty causing ls to list CWD, returning a wrong filename.
# The correct fix: use find-based detection (already used 7 lines later at :486).
# [BUG from Gap Iteration Spec Audit — 2026-04-16]
# Skip guard: set BUG_SKIP_M12=0 to enable
# Fix: quality/patches/BUG-M12-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M12_test_file_ext_ls_glob_false_positive() {
    if [ "${BUG_SKIP_M12:-1}" = "1" ]; then
        echo "  SKIP: BUG-M12 skip guard active (set BUG_SKIP_M12=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local gate="${GATE_SH_PATH:-quality_gate.sh}"

    if [ ! -f "$gate" ]; then
        echo "  SKIP: quality_gate.sh not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: line 479 uses ls-glob instead of find
    if grep -qE 'func_test=\$\(ls [^)]*test_functional\.\*' "$gate"; then
        echo "  BUG CONFIRMED: quality_gate.sh uses ls-glob for func_test assignment (vulnerable to nullglob)"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: func_test assignment uses find-based detection"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-M13: ls-glob in code_reviews directory check (quality_gate.sh:143)
#
# The bug: `[ -n "$(ls ${q}/code_reviews/*.md 2>/dev/null)" ]` uses ls-glob
# for presence detection. Under nullglob + empty directory, ls lists CWD,
# returning non-empty result — FALSE PASS for missing code review artifacts.
# [BUG from Gap Iteration Spec Audit — 2026-04-16]
# Skip guard: set BUG_SKIP_M13=0 to enable
# Fix: quality/patches/BUG-M13-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M13_code_reviews_ls_glob_false_pass() {
    if [ "${BUG_SKIP_M13:-1}" = "1" ]; then
        echo "  SKIP: BUG-M13 skip guard active (set BUG_SKIP_M13=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local gate="${GATE_SH_PATH:-quality_gate.sh}"

    if [ ! -f "$gate" ]; then
        echo "  SKIP: quality_gate.sh not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: code_reviews check uses ls-glob instead of find
    if grep -qE '\$\(ls [^)]*code_reviews/\*\.md' "$gate"; then
        echo "  BUG CONFIRMED: quality_gate.sh:143 uses ls-glob for code_reviews detection (vulnerable to nullglob)"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: code_reviews check uses find-based detection"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L14: Wrong recommendation enum values in references/review_protocols.md:410
#
# The bug: references/review_protocols.md:410 specifies template values
# "SHIP IT / FIX FIRST / NEEDS INVESTIGATION" but quality_gate.sh:427 validates
# only "SHIP", "FIX BEFORE MERGE", "BLOCK". Agents following the reference file
# produce gate-failing integration-results.json artifacts.
# [BUG from Gap Iteration Spec Audit — 2026-04-16]
# Skip guard: set BUG_SKIP_L14=0 to enable
# Fix: quality/patches/BUG-L14-fix.patch
# ---------------------------------------------------------------------------
test_BUG_L14_recommendation_enum_inconsistency() {
    if [ "${BUG_SKIP_L14:-1}" = "1" ]; then
        echo "  SKIP: BUG-L14 skip guard active (set BUG_SKIP_L14=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local ref="${REF_DIR:-references}/review_protocols.md"

    if [ ! -f "$ref" ]; then
        echo "  SKIP: references/review_protocols.md not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: stale enum values present in reference file
    if grep -q 'SHIP IT' "$ref" && grep -q 'FIX FIRST' "$ref"; then
        echo "  BUG CONFIRMED: references/review_protocols.md contains stale enum values (SHIP IT / FIX FIRST)"
        echo "  Gate expects: SHIP | FIX BEFORE MERGE | BLOCK"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: review_protocols.md uses canonical enum values"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-M15: No recheck-results.json validation in quality_gate.sh
#
# The bug: quality_gate.sh has zero validation for recheck-results.json or
# recheck-summary.md despite SKILL.md artifact contract table documenting both
# as required artifacts when recheck mode runs. An incorrect recheck artifact
# passes all gate checks silently.
# [BUG from Gap Iteration Spec Audit — 2026-04-16]
# Skip guard: set BUG_SKIP_M15=0 to enable
# Fix: quality/patches/BUG-M15-fix.patch
# ---------------------------------------------------------------------------
test_BUG_M15_no_recheck_validation() {
    if [ "${BUG_SKIP_M15:-1}" = "1" ]; then
        echo "  SKIP: BUG-M15 skip guard active (set BUG_SKIP_M15=0 to run red phase)"
        SKIP=$((SKIP + 1))
        return 0
    fi

    local gate="${GATE_SH_PATH:-quality_gate.sh}"

    if [ ! -f "$gate" ]; then
        echo "  SKIP: quality_gate.sh not found"
        SKIP=$((SKIP + 1))
        return 0
    fi

    # BUG CONFIRMATION: no recheck validation anywhere in gate
    if grep -q 'recheck' "$gate"; then
        echo "  BUG FIXED: quality_gate.sh now contains recheck validation"
        return 0
    else
        echo "  BUG CONFIRMED: quality_gate.sh has no validation for recheck-results.json or recheck-summary.md"
        return 1  # FAILS on unpatched code (red phase)
    fi
}

# ---------------------------------------------------------------------------
# BUG-M16: functional test existence check uses ls-glob (nullglob vulnerable)
# ---------------------------------------------------------------------------
: "${BUG_SKIP_M16:=1}"
test_BUG_M16_functional_test_existence_nullglob() {
    if [ "$BUG_SKIP_M16" -ne 0 ]; then
        echo "SKIP: test_BUG_M16_functional_test_existence_nullglob (BUG_SKIP_M16=${BUG_SKIP_M16})"
        return 77
    fi
    echo "TEST: test_BUG_M16_functional_test_existence_nullglob"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # The bug: line 124 uses ls-glob, not find-based detection
    # A find-based check would look like: find "${q}" -maxdepth 1 -name "test_functional.*" -print -quit | grep -q .
    # The vulnerable pattern: if ls ${q}/test_functional.* ...
    if grep -qE 'if ls \$\{q\}/test_functional\.' "$gate"; then
        echo "  BUG CONFIRMED: quality_gate.sh:124 uses ls-glob for functional test existence (nullglob vulnerable)"
        return 1  # FAILS on unpatched code (red phase)
    elif grep -qE 'find.*test_functional.*print.*quit.*grep -q' "$gate" || \
         grep -n 'test_functional' "$gate" | grep -q 'find'; then
        echo "  BUG FIXED: quality_gate.sh now uses find-based functional test existence check"
        return 0
    else
        echo "  INDETERMINATE: cannot confirm presence of ls-glob or find-based check at line 124"
        return 2
    fi
}

# ---------------------------------------------------------------------------
# BUG-H17: BUG-[0-9]+ regex never matches severity-prefix IDs (BUG-H1 format)
# ---------------------------------------------------------------------------
: "${BUG_SKIP_H17:=1}"
test_BUG_H17_bug_id_regex_bypasses_severity_prefix() {
    if [ "$BUG_SKIP_H17" -ne 0 ]; then
        echo "SKIP: test_BUG_H17_bug_id_regex_bypasses_severity_prefix (BUG_SKIP_H17=${BUG_SKIP_H17})"
        return 77
    fi
    echo "TEST: test_BUG_H17_bug_id_regex_bypasses_severity_prefix"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # Direct proof: the regex BUG-[0-9]+ does not match BUG-H1
    local match
    match=$(echo '### BUG-H1' | grep -cE '^### BUG-[0-9]+' || true)
    if [ "$match" -eq 0 ]; then
        echo "  BUG CONFIRMED: regex '^### BUG-[0-9]+' returns 0 matches for '### BUG-H1'"
        echo "  Consequence: bug_count=0 for any BUGS.md using severity-prefix IDs"
        echo "  Gate then skips ALL TDD/patch/writeup validation (lines 223,309,564,592)"
        # Also verify the gate actually uses this regex
        if grep -qE "grep -cE '\^### BUG-\[0-9\]\+'" "$gate" || \
           grep -q "BUG-\[0-9\]" "$gate"; then
            echo "  Gate confirmed to use BUG-[0-9]+ regex — bug is present in unpatched code"
        fi
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: regex now matches severity-prefix IDs (BUG-H1 format matches)"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-M18: TDD sidecar JSON phase values not cross-validated against log tags
# ---------------------------------------------------------------------------
: "${BUG_SKIP_M18:=1}"
test_BUG_M18_red_phase_log_cross_validation() {
    if [ "$BUG_SKIP_M18" -ne 0 ]; then
        echo "SKIP: test_BUG_M18_red_phase_log_cross_validation (BUG_SKIP_M18=${BUG_SKIP_M18})"
        return 77
    fi
    echo "TEST: test_BUG_M18_red_phase_log_cross_validation"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # The cross-validation that MUST exist per SKILL.md:1589:
    #   Extract json_str_val for "red_phase", compare with first line of BUG-NNN.red.log
    # Proxy: look for code that reads red_phase VALUE (not just checks key presence)
    # json_key_count checks presence; json_str_val extracts value
    # Cross-validation would combine json_str_val "red_phase" with comparison against log tag
    local has_cross_val=0
    # Check for a pattern that extracts red_phase value AND compares with log tag
    if grep -A5 'red_phase\|green_phase' "$gate" | grep -q 'json_str_val'; then
        has_cross_val=1
    fi
    if grep -q 'red_phase.*red_tag\|red_tag.*red_phase\|green_phase.*green_tag\|green_tag.*green_phase' "$gate"; then
        has_cross_val=1
    fi
    if [ "$has_cross_val" -eq 0 ]; then
        echo "  BUG CONFIRMED: no cross-validation between tdd-results.json phase values and log tags"
        echo "  SKILL.md:1589 mandates: if red_phase='pass' in JSON, BUG-NNN.red.log first line must be RED"
        echo "  Gate validates field presence (lines 239-248) and tag format (lines 322-325) independently"
        echo "  But never compares them — contradiction between JSON and log goes undetected"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: cross-validation between sidecar JSON phase values and log tags is present"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L19: Summary sub-key check uses json_has_key (weak) instead of json_key_count (strong)
# quality_gate.sh:259-265 uses json_has_key for summary keys while lines 239-248 use json_key_count
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L19:=1}"
test_BUG_L19_summary_check_uses_weak_json_has_key() {
    if [ "$BUG_SKIP_L19" -ne 0 ]; then
        echo "SKIP: test_BUG_L19_summary_check_uses_weak_json_has_key (BUG_SKIP_L19=${BUG_SKIP_L19})"
        return 77
    fi
    echo "TEST: test_BUG_L19_summary_check_uses_weak_json_has_key"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # Check that line 262 (or nearby) uses json_has_key for summary skey loop
    # The bug: for skey in total verified ...; do if json_has_key "$json_file" "$skey"
    # while per-bug check uses json_key_count
    local summary_check_pattern
    summary_check_pattern=$(grep -n 'json_has_key.*json_file.*skey\|skey.*json_has_key' "$gate" | head -5)
    if [ -n "$summary_check_pattern" ]; then
        echo "  BUG CONFIRMED: json_has_key used for summary sub-key checks: $summary_check_pattern"
        echo "  Per-bug check at lines 239-248 uses json_key_count (stronger colon-anchored pattern)"
        echo "  Inconsistency: two parallel required-field checks use different validators"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: summary check now uses json_key_count consistently"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L20: Patch existence uses aggregate count instead of per-bug iteration
# quality_gate.sh:562-588 counts patches in aggregate; lines 316-345 iterates per bug ID
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L20:=1}"
test_BUG_L20_patch_count_aggregate_vs_per_bug() {
    if [ "$BUG_SKIP_L20" -ne 0 ]; then
        echo "SKIP: test_BUG_L20_patch_count_aggregate_vs_per_bug (BUG_SKIP_L20=${BUG_SKIP_L20})"
        return 77
    fi
    echo "TEST: test_BUG_L20_patch_count_aggregate_vs_per_bug"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # Check that lines 562-588 use aggregate count (not per-bug iteration)
    # The bug: reg_patch_count=$(ls ${q}/patches/BUG-*-regression*.patch ... | wc -l)
    # compared to TDD log section which uses: for bid in $bug_ids; do
    local aggregate_patch_count
    aggregate_patch_count=$(grep -n 'reg_patch_count=\$(ls.*patches.*BUG-\*' "$gate" | head -3)
    if [ -n "$aggregate_patch_count" ]; then
        echo "  BUG CONFIRMED: aggregate patch count pattern found: $aggregate_patch_count"
        echo "  Log check at lines 316-345 iterates per bug ID (correct)"
        echo "  Patch check uses aggregate count — cannot detect missing patch for specific bug"
        echo "  Concrete false-pass: 2 bugs, 2 copies of BUG-H1 patch, BUG-M3 patch absent → PASS"
        return 1  # FAILS on unpatched code (red phase)
    else
        echo "  BUG FIXED: patch check now iterates per-bug ID like TDD log check"
        return 0
    fi
}

# ---------------------------------------------------------------------------
# BUG-L21: Phase 5 has no entry gate for Phase 4 artifacts (spec bug — SKILL.md)
# SKILL.md:1573-1590 has no entry gate; compare SKILL.md:897-907 (Phase 2 entry gate)
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L21:=1}"
test_BUG_L21_phase5_no_entry_gate() {
    if [ "$BUG_SKIP_L21" -ne 0 ]; then
        echo "SKIP: test_BUG_L21_phase5_no_entry_gate (BUG_SKIP_L21=${BUG_SKIP_L21})"
        return 77
    fi
    echo "TEST: test_BUG_L21_phase5_no_entry_gate"
    local skill_md="${SKILL_PATH:-SKILL.md}"
    # Check: Phase 2 has entry gate text; Phase 5 opening should also have entry gate text
    # Phase 2 gate: "Phase 2 entry gate (mandatory — HARD STOP)"
    local phase2_gate
    phase2_gate=$(grep -n 'Phase 2 entry gate.*mandatory.*HARD STOP\|mandatory.*HARD STOP.*Phase 2' "$skill_md" | head -1)
    # Phase 5 opening — look for equivalent "Phase 5 entry gate" text
    local phase5_gate
    phase5_gate=$(grep -n 'Phase 5 entry gate\|Phase 5.*entry gate.*mandatory' "$skill_md" | head -1)
    if [ -n "$phase2_gate" ] && [ -z "$phase5_gate" ]; then
        echo "  BUG CONFIRMED: Phase 2 has entry gate ('$phase2_gate') but Phase 5 has none"
        echo "  Phase 2 gate fires BEFORE any Phase 2 work; Phase 5 only has terminal gate at END"
        echo "  An agent can proceed through all of Phase 5 with no Phase 4 artifacts"
        return 1  # FAILS on unpatched code (red phase)
    elif [ -n "$phase5_gate" ]; then
        echo "  BUG FIXED: Phase 5 now has entry gate: $phase5_gate"
        return 0
    else
        echo "  INCONCLUSIVE: Phase 2 gate text not found — check SKILL.md structure"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# BUG-L22: SEED_CHECKS.md absent from artifact contract table (spec bug — SKILL.md)
# SKILL.md:1641 requires SEED_CHECKS.md; SKILL.md:88-119 table omits it
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L22:=1}"
test_BUG_L22_seed_checks_absent_from_artifact_table() {
    if [ "$BUG_SKIP_L22" -ne 0 ]; then
        echo "SKIP: test_BUG_L22_seed_checks_absent_from_artifact_table (BUG_SKIP_L22=${BUG_SKIP_L22})"
        return 77
    fi
    echo "TEST: test_BUG_L22_seed_checks_absent_from_artifact_table"
    local skill_md="${SKILL_PATH:-SKILL.md}"
    # Check that SKILL.md:1641 requires SEED_CHECKS.md (Phase 5 gate)
    local phase5_requirement
    phase5_requirement=$(grep -n 'SEED_CHECKS' "$skill_md" | grep -v '^#' | head -5)
    # Check that SEED_CHECKS.md is in the artifact contract table (lines 88-119)
    local table_entry
    table_entry=$(awk 'NR>=88 && NR<=125' "$skill_md" | grep -i 'SEED_CHECKS')
    if [ -n "$phase5_requirement" ] && [ -z "$table_entry" ]; then
        echo "  BUG CONFIRMED: SEED_CHECKS.md required by Phase 5 (line: $phase5_requirement)"
        echo "  But SEED_CHECKS.md is NOT in the canonical artifact contract table (lines 88-119)"
        echo "  Table claims to be canonical: 'any artifact not listed here should not be gate-enforced'"
        echo "  Self-contradiction: required by Phase 5 gate, absent from canonical table"
        return 1  # FAILS on unpatched code (red phase)
    elif [ -n "$table_entry" ]; then
        echo "  BUG FIXED: SEED_CHECKS.md now appears in artifact contract table: $table_entry"
        return 0
    else
        echo "  INCONCLUSIVE: SEED_CHECKS.md not found in Phase 5 requirement text"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# BUG-L23: integration-results.json groups[].result enum not validated by gate
# quality_gate.sh:389-436 has no check for groups[].result valid values
# SKILL.md:1273 defines valid values: "pass", "fail", "skipped", "error"
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L23:=1}"
test_BUG_L23_integration_groups_result_enum_absent() {
    if [ "$BUG_SKIP_L23" -ne 0 ]; then
        echo "SKIP: test_BUG_L23_integration_groups_result_enum_absent (BUG_SKIP_L23=${BUG_SKIP_L23})"
        return 77
    fi
    echo "TEST: test_BUG_L23_integration_groups_result_enum_absent"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # The gate SHOULD validate groups[].result enum values — check that it does NOT (red phase)
    local result_enum_check
    result_enum_check=$(grep -n 'result.*pass\|result.*fail\|groups\[\]\|result_enum' "$gate" | grep -v '^#' | head -10)
    # Also verify tdd verdict enum IS validated (for contrast)
    local tdd_verdict_check
    tdd_verdict_check=$(grep -n '"open"\|"confirmed_open"\|"closed"\|verdict.*enum\|VERDICT' "$gate" | grep -v '^#' | head -5)
    if [ -z "$result_enum_check" ] && [ -n "$tdd_verdict_check" ]; then
        echo "  BUG CONFIRMED: integration groups[].result enum NOT validated in gate"
        echo "  No grep for result enum values in quality_gate.sh:389-436"
        echo "  Contrast: tdd verdict enum IS validated at: $tdd_verdict_check"
        echo "  SKILL.md:1273 defines valid result values: pass, fail, skipped, error"
        echo "  An agent writing result: 'PASS' (wrong case) passes gate — bug undetected"
        return 1  # FAILS on unpatched code (red phase)
    elif [ -n "$result_enum_check" ]; then
        echo "  BUG FIXED: groups[].result enum validation now present: $result_enum_check"
        return 0
    else
        echo "  INCONCLUSIVE: tdd verdict check not found either"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# BUG-L24: integration-results.json summary sub-keys not validated by gate
# quality_gate.sh:393 checks summary key presence only; sub-keys never checked
# SKILL.md:1252-1255 defines 4 required sub-keys: total_groups, passed, failed, skipped
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L24:=1}"
test_BUG_L24_integration_summary_subkeys_absent() {
    if [ "$BUG_SKIP_L24" -ne 0 ]; then
        echo "SKIP: test_BUG_L24_integration_summary_subkeys_absent (BUG_SKIP_L24=${BUG_SKIP_L24})"
        return 77
    fi
    echo "TEST: test_BUG_L24_integration_summary_subkeys_absent"
    local gate="${GATE_PATH:-repos/quality_gate.sh}"
    # The gate should validate integration summary sub-keys — check that it does NOT (red phase)
    local int_summary_subkey_check
    int_summary_subkey_check=$(grep -n 'total_groups\|integration.*summary\|summary.*total_groups' "$gate" | grep -v '^#' | head -5)
    # Verify tdd summary sub-keys ARE checked (for contrast)
    local tdd_summary_subkey_check
    tdd_summary_subkey_check=$(grep -n 'total\|verified\|confirmed_open\|red_failed\|green_failed' "$gate" | grep -v '^#' | head -5)
    if [ -z "$int_summary_subkey_check" ] && [ -n "$tdd_summary_subkey_check" ]; then
        echo "  BUG CONFIRMED: integration summary sub-keys NOT validated in gate"
        echo "  No check for total_groups, passed, failed, skipped in quality_gate.sh"
        echo "  Contrast: tdd summary sub-keys ARE validated: $tdd_summary_subkey_check"
        echo "  SKILL.md:1252-1255 requires sub-keys: total_groups, passed, failed, skipped"
        echo "  An integration-results.json with empty summary{} passes gate undetected"
        return 1  # FAILS on unpatched code (red phase)
    elif [ -n "$int_summary_subkey_check" ]; then
        echo "  BUG FIXED: integration summary sub-key validation now present: $int_summary_subkey_check"
        return 0
    else
        echo "  INCONCLUSIVE: tdd summary sub-key check not found either"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# BUG-L25: Phase 2 entry gate omits Phase 1 completion gate check #1 (120-line min)
# SKILL.md:850 (Phase 1 gate check #1): "at least 120 lines of substantive content"
# SKILL.md:897-904 (Phase 2 entry gate): 6 checks, none include 120-line minimum
# BUG-M3 fix adds checks 2,3,5,8,10,12 but NOT check #1
# ---------------------------------------------------------------------------
: "${BUG_SKIP_L25:=1}"
test_BUG_L25_phase2_entry_gate_missing_check1() {
    if [ "$BUG_SKIP_L25" -ne 0 ]; then
        echo "SKIP: test_BUG_L25_phase2_entry_gate_missing_check1 (BUG_SKIP_L25=${BUG_SKIP_L25})"
        return 77
    fi
    echo "TEST: test_BUG_L25_phase2_entry_gate_missing_check1"
    local skill_md="${SKILL_PATH:-SKILL.md}"
    # Verify Phase 1 gate does have the 120-line check
    local phase1_120_check
    phase1_120_check=$(grep -n '120' "$skill_md" | grep -i 'line\|substan\|content' | head -5)
    # Check Phase 2 entry gate section (lines 897-920 approx) for 120-line check
    local phase2_120_check
    phase2_120_check=$(awk 'NR>=890 && NR<=940' "$skill_md" | grep '120')
    if [ -n "$phase1_120_check" ] && [ -z "$phase2_120_check" ]; then
        echo "  BUG CONFIRMED: Phase 1 gate has 120-line check, Phase 2 entry gate does NOT"
        echo "  Phase 1 check #1 at: $phase1_120_check"
        echo "  Phase 2 entry gate (lines 890-940): no 120-line minimum check found"
        echo "  After BUG-M3 fix: thin EXPLORATION.md (~15 lines) still passes Phase 2 entry gate"
        return 1  # FAILS on unpatched code (red phase)
    elif [ -n "$phase2_120_check" ]; then
        echo "  BUG FIXED: Phase 2 entry gate now includes 120-line check: $phase2_120_check"
        return 0
    else
        echo "  INCONCLUSIVE: Phase 1 check #1 (120-line) not found at expected location"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Run tests
# ---------------------------------------------------------------------------
echo "=== Regression Tests: quality-playbook ==="
echo "Date: 2026-04-16"
echo "All tests are skip-guarded. Set BUG_SKIP_NNN=0 to enable individual tests."
echo ""

if [ $# -gt 0 ]; then
    # Run specific test by name
    run_test "$1"
else
    run_test test_BUG_H1_json_has_key_false_positive
    run_test test_BUG_H2_array_expansion_corrupts_spaces
    run_test test_BUG_M3_phase2_gate_missing_checks
    run_test test_BUG_M4_gate_missing_regression_file_check
    run_test test_BUG_M5_phase0b_skips_on_empty_previous_runs
    run_test test_BUG_L6_json_str_val_non_string_empty
    run_test test_BUG_L7_version_string_consistency
    # Phase 4 spec audit additions
    run_test test_BUG_M8_nullglob_ls_counting
    run_test test_BUG_L9_auditor_naming_inconsistency
    run_test test_BUG_L10_recheck_schema_version_inconsistency
    run_test test_BUG_L11_tdd_results_two_incompatible_templates
    # Gap iteration additions (2026-04-16)
    run_test test_BUG_M12_test_file_ext_ls_glob_false_positive
    run_test test_BUG_M13_code_reviews_ls_glob_false_pass
    run_test test_BUG_L14_recommendation_enum_inconsistency
    run_test test_BUG_M15_no_recheck_validation
    # Unfiltered iteration additions (2026-04-16)
    run_test test_BUG_M16_functional_test_existence_nullglob
    run_test test_BUG_H17_bug_id_regex_bypasses_severity_prefix
    run_test test_BUG_M18_red_phase_log_cross_validation
    # Parity iteration additions (2026-04-16)
    run_test test_BUG_L19_summary_check_uses_weak_json_has_key
    run_test test_BUG_L20_patch_count_aggregate_vs_per_bug
    run_test test_BUG_L21_phase5_no_entry_gate
    run_test test_BUG_L22_seed_checks_absent_from_artifact_table
    # Adversarial iteration additions (2026-04-16)
    run_test test_BUG_L23_integration_groups_result_enum_absent
    run_test test_BUG_L24_integration_summary_subkeys_absent
    run_test test_BUG_L25_phase2_entry_gate_missing_check1
fi

echo ""
echo "==========================================="
echo "Results: ${PASS} PASS, ${FAIL} FAIL, ${SKIP} SKIP"
[ "$FAIL" -eq 0 ]
