#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.3 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-04-28 · Project: quality-playbook

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MECH_DIR="${ROOT_DIR}/quality/mechanical"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

python3 - <<'PY' > "${TMP_DIR}/phase2_gate_required_headings.txt"
from pathlib import Path
import re
text = Path(".github/skills/SKILL.md").read_text(encoding="utf-8")
start = text.index("**Phase 2 entry gate (mandatory — HARD STOP).**")
end = text.index("Use `quality/EXPLORATION.md` as your primary source", start)
for line in text[start:end].splitlines():
    line = line.strip()
    if re.match(r"^\d+\.\s+`", line):
        print(line)
PY

python3 - <<'PY' > "${TMP_DIR}/phase2_gate_runtime_contract.txt"
from pathlib import Path
text = Path("bin/run_playbook.py").read_text(encoding="utf-8")
start = text.index('if phase == "2":')
end = text.index('if phase == "3":', start)
print(text[start:end].strip())
PY

python3 - <<'PY' > "${TMP_DIR}/project_type_classifier_values.txt"
from bin import classify_project
for value in classify_project.VALID_CLASSIFICATIONS:
    print(value)
PY

python3 - <<'PY' > "${TMP_DIR}/index_writer_project_type_literals.txt"
from pathlib import Path
for line in Path("bin/run_playbook.py").read_text(encoding="utf-8").splitlines():
    if "target_project_type" in line:
        print(line.strip())
PY

python3 - <<'PY' > "${TMP_DIR}/citation_install_copy_commands.txt"
from pathlib import Path
text = Path("repos/setup_repos.sh").read_text(encoding="utf-8").splitlines()
capture = False
for line in text:
    if "# Install skill files" in line:
        capture = True
    if capture:
        print(line.rstrip())
    if 'log "  ✓ ${short}-${VERSION} ready"' in line:
        break
PY

python3 - <<'PY' > "${TMP_DIR}/skill_entry_hashes.txt"
import hashlib
from pathlib import Path
for rel in ("SKILL.md", ".github/skills/SKILL.md"):
    data = Path(rel).read_bytes()
    print(f"{hashlib.sha256(data).hexdigest()}  {rel}")
PY

for name in \
    phase2_gate_required_headings.txt \
    phase2_gate_runtime_contract.txt \
    project_type_classifier_values.txt \
    index_writer_project_type_literals.txt \
    citation_install_copy_commands.txt \
    skill_entry_hashes.txt
do
    diff -u "${MECH_DIR}/${name}" "${TMP_DIR}/${name}"
done

echo "mechanical verify: PASS"
